"""LLM agent that simplifies a generated T-SQL stored procedure.

The generated SQL is a direct one-tool-per-CTE translation of an Alteryx
workflow, which produces many redundant pass-through CTEs and split
join/union patterns.  This agent sends the full SQL in one shot to Gemini
Flash (1M-token context, no chunking needed) and returns a shorter,
functionally equivalent version.

Usage:
    from llm.sql_enhancer import enhance_sql
    enhanced = enhance_sql(sql_text)
"""

from __future__ import annotations

import os
import time

from pydantic_ai import Agent
from pydantic_ai.settings import ModelSettings

from llm.settings import get_settings

_MAX_RETRIES = 4
_RETRY_BASE_DELAY = 10.0  # seconds; doubles each attempt (10 → 20 → 40 → 80)

_SYSTEM_PROMPT = """\
You are a T-SQL refactoring expert. You receive a stored procedure that was machine-generated by translating an Alteryx workflow one tool at a time, resulting in highly redundant intermediate steps. Simplify it to highly optimized T-SQL while preserving exact logical behavior and row counts.

Simplification rules — apply all that are safe:

1. SEQUENTIAL FORMULA CTEs: When consecutive CTEs each add only one or two computed columns and pass everything else through unchanged, collapse them into a single CTE that computes all derived columns in one SELECT.

2. AGGREGATE & JOIN REPLACEMENT: Alteryx workflows often use a Summarize tool followed by a Join to append aggregates (like Counts or Sums) back to the detail rows. Replace this pattern entirely with Window Functions (e.g., COUNT(*) OVER(PARTITION BY...)) to avoid redundant group-by joins.

3. SPLIT JOIN+UNION PATTERN: When you see an INNER JOIN branch that filters and renames columns, combined via UNION ALL with a LEFT JOIN unmatched-only branch, replace both with a single LEFT JOIN + WHERE + CASE expression. 

4. MULTI-OUTPUT BRANCHING: If the workflow splits into multiple destination tables at the end, compute all shared logic in CTEs, dump the final shared state into a single #TempTable, and use that #TempTable to generate the multiple final outputs.

5. TRIVIAL PASS-THROUGHS & DEAD ENDS: Remove CTEs or temp tables that only rename or reorder columns (inline the renames at the point of use). If an intermediate CTE is created but never referenced by any downstream CTE or output block, drop it entirely — no replacement comment, just delete it.

6. SOURCE COLUMN PRUNING & UNWRAPPING: Un-wrap simple STUB SELECTs (e.g., SELECT * INTO #t FROM (-- STUB SELECT cols FROM T) AS [_src]; → -- STUB\nSELECT cols INTO #t FROM T;). Only load columns that are explicitly referenced downstream; drop the rest.

7. JOIN PARITY: Alteryx joins behave differently than SQL INNER JOINs. Ensure that joins on lookup tables do not accidentally multiply rows. If a lookup source might have duplicates, use ROW_NUMBER() OVER(...) to deduplicate it before joining.

Constraints you must respect:
- OUTPUT DESTINATION BLOCKS: Any temp table whose body contains "-- Output destination:" is a workflow output. NEVER remove, inline, or rename it. NEVER strip its comment block. Preserve the entire temp table exactly as written, including all comment lines (-- Output destination: ..., -- Replace trailing SELECT with:, --   INSERT INTO ...). These are the final write targets of the workflow — they are never dead ends even though nothing reads from them downstream.
- Keep ALL -- !!! STUB — requires manual review !!! comments exactly as-is, but only for stubs that are actually referenced downstream. A stub CTE/temp table that is a dead end (no output destination comment, nothing reads from it) should be deleted entirely — do not add any comment explaining the deletion.
- Keep all VALUES(...) inline data intact (do not summarize or truncate it).
- All SQL must remain valid T-SQL / Microsoft SQL Server syntax.
- Use descriptive _underscore_prefixed names for collapsed CTEs.
- Output ONLY the complete stored procedure — no explanation, no markdown fences, no preamble. Start directly with the -- === header comment block.
"""


_TIMEOUT_SECONDS = 600  # large SQL files can take several minutes to enhance


def _make_agent() -> Agent:
    settings = get_settings()
    os.environ.setdefault("GOOGLE_CLOUD_PROJECT", settings.vertex_project)
    os.environ.setdefault("GOOGLE_CLOUD_LOCATION", settings.vertex_location)
    return Agent(
        settings.model_id,
        output_type=str,
        system_prompt=_SYSTEM_PROMPT,
        retries=1,
        model_settings=ModelSettings(timeout=_TIMEOUT_SECONDS),
    )


def enhance_sql(sql: str) -> str:
    """Send *sql* to Gemini Flash and return a simplified equivalent.

    Sends the full procedure in one prompt — Gemini Flash's 1M-token context
    handles even large generated files without chunking.

    Returns the raw LLM output string; caller is responsible for writing to disk.
    Raises on LLM failure so the caller can report and skip gracefully.
    """
    agent = _make_agent()
    delay = _RETRY_BASE_DELAY
    for attempt in range(_MAX_RETRIES):
        try:
            result = agent.run_sync(sql)
            return result.output.strip()
        except Exception as exc:
            if attempt == _MAX_RETRIES - 1:
                raise
            exc_str = str(exc)
            retryable = "429" in exc_str or "RESOURCE_EXHAUSTED" in exc_str or "499" in exc_str or "CANCELLED" in exc_str
            if not retryable:
                raise
            time.sleep(delay)
            delay *= 2
    raise RuntimeError("unreachable")
