"""LLM agent that simplifies a generated T-SQL stored procedure.

The generated SQL is a direct one-tool-per-CTE translation of an Alteryx
workflow, which produces many redundant pass-through CTEs and split
join/union patterns.  This agent sends the full SQL in one shot to Gemini
Flash (1M-token context, no chunking needed) and returns a shorter,
functionally equivalent version.

Usage:
    from llm.sql_enhancer import enhance_sql
    enhanced = enhance_sql(sql_text)
"""

from __future__ import annotations

import os

from pydantic_ai import Agent

from llm.settings import get_settings

_SYSTEM_PROMPT = """\
You are a T-SQL refactoring expert. You receive a stored procedure that was machine-generated by translating an Alteryx workflow one tool at a time, resulting in highly redundant intermediate steps. Simplify it to highly optimized T-SQL while preserving exact logical behavior and row counts.

Simplification rules — apply all that are safe:

1. SEQUENTIAL FORMULA CTEs: When consecutive CTEs each add only one or two computed columns and pass everything else through unchanged, collapse them into a single CTE that computes all derived columns in one SELECT.

2. AGGREGATE & JOIN REPLACEMENT: Alteryx workflows often use a Summarize tool followed by a Join to append aggregates (like Counts or Sums) back to the detail rows. Replace this pattern entirely with Window Functions (e.g., COUNT(*) OVER(PARTITION BY...)) to avoid redundant group-by joins.

3. SPLIT JOIN+UNION PATTERN: When you see an INNER JOIN branch that filters and renames columns, combined via UNION ALL with a LEFT JOIN unmatched-only branch, replace both with a single LEFT JOIN + WHERE + CASE expression. 

4. MULTI-OUTPUT BRANCHING: If the workflow splits into multiple destination tables at the end, compute all shared logic in CTEs, dump the final shared state into a single #TempTable, and use that #TempTable to generate the multiple final outputs.

5. TRIVIAL PASS-THROUGHS & DEAD ENDS: Remove CTEs or temp tables that only rename or reorder columns (inline the renames at the point of use). If an intermediate table is created but never referenced downstream, drop it entirely.

6. SOURCE COLUMN PRUNING & UNWRAPPING: Un-wrap simple STUB SELECTs (e.g., SELECT * INTO #t FROM (-- STUB SELECT cols FROM T) AS [_src]; → -- STUB\nSELECT cols INTO #t FROM T;). Only load columns that are explicitly referenced downstream; drop the rest.

7. JOIN PARITY: Alteryx joins behave differently than SQL INNER JOINs. Ensure that joins on lookup tables do not accidentally multiply rows. If a lookup source might have duplicates, use ROW_NUMBER() OVER(...) to deduplicate it before joining.

Constraints you must respect:
- Keep ALL -- !!! STUB — requires manual review !!! comments exactly as-is.
- Keep all VALUES(...) inline data intact (do not summarize or truncate it).
- All SQL must remain valid T-SQL / Microsoft SQL Server syntax.
- Use descriptive _underscore_prefixed names for collapsed CTEs.
- Output ONLY the complete stored procedure — no explanation, no markdown fences, no preamble. Start directly with the -- === header comment block.
"""


def _make_agent() -> Agent:
    settings = get_settings()
    os.environ.setdefault("GOOGLE_CLOUD_PROJECT", settings.vertex_project)
    os.environ.setdefault("GOOGLE_CLOUD_LOCATION", settings.vertex_location)
    return Agent(
        settings.model_id,
        output_type=str,
        system_prompt=_SYSTEM_PROMPT,
        retries=1,
    )


_agent: Agent | None = None


def enhance_sql(sql: str) -> str:
    """Send *sql* to Gemini Flash and return a simplified equivalent.

    Sends the full procedure in one prompt — Gemini Flash's 1M-token context
    handles even large generated files without chunking.

    Returns the raw LLM output string; caller is responsible for writing to disk.
    Raises on LLM failure so the caller can report and skip gracefully.
    """
    global _agent
    if _agent is None:
        _agent = _make_agent()
    result = _agent.run_sync(sql)
    return result.output.strip()
