"""LLM agent that simplifies a generated T-SQL stored procedure.

The generated SQL is a direct one-tool-per-CTE translation of an Alteryx
workflow, which produces many redundant pass-through CTEs and split
join/union patterns.  This agent sends the full SQL in one shot to Gemini
Flash (1M-token context, no chunking needed) and returns a shorter,
functionally equivalent version.

Usage:
    from llm.sql_enhancer import enhance_sql
    enhanced = enhance_sql(sql_text)
"""

from __future__ import annotations

import os

from pydantic_ai import Agent

from llm.settings import get_settings

_SYSTEM_PROMPT = """\
You are a T-SQL refactoring expert. You receive a stored procedure that was
machine-generated by translating an Alteryx workflow one tool at a time, so it
contains many redundant intermediate steps. Simplify it while preserving exact
logical behaviour.

Simplification rules — apply all that are safe:

1. SEQUENTIAL FORMULA CTEs: When consecutive CTEs each add only one or two
   computed columns and pass everything else through unchanged, collapse them
   into a single CTE that computes all derived columns in one SELECT.

2. SPLIT JOIN+UNION PATTERN: When you see an INNER JOIN branch that filters and
   renames columns, combined via UNION ALL with a LEFT JOIN unmatched-only
   branch, replace both with a single LEFT JOIN + WHERE + CASE expression.
   Example: inner join (matched, flag != 1) UNION ALL left join (unmatched)
   becomes: LEFT JOIN ... WHERE unmatched OR flag != 1, with CASE for
   matched/unmatched values.

3. TRIVIAL PASS-THROUGHS: Remove CTEs or temp tables that only rename or
   reorder columns — inline the renames at the point of use.

4. DEAD-END BRANCHES: If a temp table or CTE is created but never referenced
   downstream, drop it entirely.

5. SOURCE COLUMN PRUNING: In the source SELECT INTO stub temp tables, reduce
   the SELECT column list to only the columns referenced anywhere downstream;
   do not load columns that are never used.

6. STUB SOURCE UNWRAPPING: When a SELECT INTO temp table wraps a simple STUB
   SELECT … FROM <table> in a subquery, remove the wrapper entirely.
   Both forms should be collapsed:
     - "SELECT * INTO #t FROM (-- STUB SELECT cols FROM T) AS [_src];"
       → "-- STUB\nSELECT cols INTO #t FROM T;"
     - "SELECT [a],[b] INTO #t FROM (-- STUB SELECT [a],[b],[c] FROM T) AS [_src];"
       → "-- STUB\nSELECT [a],[b] INTO #t FROM T;"
   Only unwrap when the inner query is a plain SELECT … FROM <table> with no
   WHERE, JOIN, GROUP BY, or subquery. Keep the STUB comment on its own line
   before the SELECT.

7. SOURCE COLUMN PRUNING: In stub SELECT lists, include only columns that are
   referenced downstream; drop the rest.

Constraints you must respect:
- Keep ALL -- !!! STUB — requires manual review !!! comments exactly as-is.
- Keep all VALUES(...) inline data intact (do not summarise or truncate it).
- All SQL must remain valid T-SQL / Microsoft SQL Server syntax.
- Use descriptive _underscore_prefixed names for collapsed CTEs.
- Output ONLY the complete stored procedure — no explanation, no markdown
  fences, no preamble. Start directly with the -- === header comment block.
"""


def _make_agent() -> Agent:
    settings = get_settings()
    os.environ.setdefault("GOOGLE_CLOUD_PROJECT", settings.vertex_project)
    os.environ.setdefault("GOOGLE_CLOUD_LOCATION", settings.vertex_location)
    return Agent(
        settings.model_id,
        output_type=str,
        system_prompt=_SYSTEM_PROMPT,
        retries=1,
    )


_agent: Agent | None = None


def enhance_sql(sql: str) -> str:
    """Send *sql* to Gemini Flash and return a simplified equivalent.

    Sends the full procedure in one prompt — Gemini Flash's 1M-token context
    handles even large generated files without chunking.

    Returns the raw LLM output string; caller is responsible for writing to disk.
    Raises on LLM failure so the caller can report and skip gracefully.
    """
    global _agent
    if _agent is None:
        _agent = _make_agent()
    result = _agent.run_sync(sql)
    return result.output.strip()
