-- =============================================================================
-- Generated by alteryx-to-sql-agent
-- Source:    BI_Aggregate Daily Simple_LDB-01.yxmd
-- Generated: 2026-04-09 11:56:54 UTC
-- Stubs:     8 CTE(s) require manual review
-- =============================================================================

WITH
[cte_db_file_input_2] AS (
    select * 
    from Publications
),

[cte_text_input_14] AS (
    SELECT NULL AS [logged_varenummer], NULL AS [logged_hostname], NULL AS [alter_varenummer], NULL AS [alter_hostname], NULL AS [kommentar], NULL AS [demo_url] WHERE 1 = 0
),

[cte_db_file_input_29] AS (
    select * 
    from CUSTTABLE
),

[cte_db_file_input_50] AS (
    select * 
    from accounting
),

[cte_text_input_66] AS (
    SELECT NULL AS [CompanyName], NULL AS [CompanyAddress], NULL AS [CompanyZipCity], NULL AS [CompanyCountry], NULL AS [ParentCompanyID], NULL AS [companyType], NULL AS [CompanyID] WHERE 1 = 0
),

[cte_db_file_input_71] AS (
    select * 
    from StudyBoxUsers
),

[cte_select_36] AS (
    SELECT
        [ITEMNUMBER] AS [ItemNumber],
        [INV_MAINITEM] AS [MainItemNumber],
        [ITEMNAME1] AS [PublicationName],
        [UNITCODE] AS [Unit],
        [ENUMTXT_Publicationstatus] AS [Status],
        [ENUMTXT_Forlag] AS [PublisherERP],
        [INV_REDINTERN] AS [EditorInternal],
        [PROJLEADER] AS [ProjectManager],
        [PRODLEADER] AS [LD],
        [COMMANAGER] AS [CommunicationManager],
        [GROUPNAME] AS [PublicationMainSubject],
        [*Unknown]
    FROM [cte_db_file_input_2]
),

[cte_select_6] AS (
    SELECT
        [logged_varenummer],
        [alter_varenummer],
        [*Unknown]
    FROM [cte_text_input_14]
),

[cte_filter_30] AS (
    SELECT *
    FROM [cte_db_file_input_29]
    WHERE [DATASET] = 'DAT'
),

[cte_select_86] AS (
    SELECT
        [mainUserSubject] AS [UserSubject],
        [hashedUserid] AS [eKeysUser],
        [*Unknown]
    FROM [cte_db_file_input_50]
),

[cte_select_89] AS (
    SELECT
        [Studieretning] AS [UserSubject],
        [Dato] AS [CreatedDate],
        [Institutionens ID] AS [companyId],
        [Institutionens navn] AS [CompanyName],
        [*Unknown]
    FROM [cte_db_file_input_71]
),

[cte_macro_31] AS (
    -- !!! STUB — requires manual review !!!
    -- TODO: expand macro 'Cleanse.yxmc'
    -- Reads from: cte_filter_30
    SELECT TOP 0 1 AS _macro_stub  -- replace with macro logic
),

[cte_formula_38] AS (
    -- !!! STUB — requires manual review !!!
    SELECT
        *,
        NULL AS [SchoolYear]  -- TODO: -- LLM conversion failed: Unknown keyword arguments: `result_type`,
        ToDate([timestamp]) AS [Date]
    FROM [cte_select_86]
),

[cte_filter_45] AS (
    SELECT *
    FROM [cte_macro_31]
    WHERE IsInteger([ACCOUNT])
),

[cte_formula_87] AS (
    -- !!! STUB — requires manual review !!!
    SELECT
        *,
        NULL AS [MainUserType]  -- TODO: -- LLM conversion failed: Unknown keyword arguments: `result_type`,
        1 AS [PageViews]
    FROM [cte_formula_38]
),

[cte_formula_43] AS (
    SELECT
        *,
        TRY_CAST([ACCOUNT] AS FLOAT) AS [CompanyID]
    FROM [cte_filter_45]
),

[cte_formula_15] AS (
    -- !!! STUB — requires manual review !!!
    SELECT
        *,
        NULL AS [ops_varenummer]  -- TODO: -- LLM conversion failed: Unknown keyword arguments: `result_type`
    FROM [cte_formula_87]
),

[cte_select_44] AS (
    SELECT
        [NAME] AS [CompanyName],
        [ADDRESS1] AS [CompanyAddress],
        [ZIPCITY] AS [CompanyZipCity],
        [COUNTRY] AS [CompanyCountry],
        [INVOICEACCOUNT] AS [ParentCompanyID],
        [GROUP_] AS [companyType],
        [CompanyID]
    FROM [cte_formula_43]
),

[cte_record_id_20] AS (
    SELECT
        *,
        ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS [RecordID]
    FROM [cte_formula_15]
),

[cte_union_67] AS (
    -- UNION ALL preserves duplicates. Change to UNION to deduplicate.
    SELECT * FROM [cte_select_44]
    UNION ALL
    SELECT * FROM [cte_text_input_66]
),

[cte_formula_12] AS (
    -- !!! STUB — requires manual review !!!
    SELECT
        *,
        NULL AS [UserSubject]  -- TODO: -- LLM conversion failed: Unknown keyword arguments: `result_type`
    FROM [cte_record_id_20]
),

[cte_join_4] AS (
    -- Join anchor output (matched rows)
    -- Left-only:  add WHERE R.[logged_hostname] IS NULL
    -- Right-only: add WHERE L.[hostname] IS NULL
    SELECT
        L.*,
        R.*
    FROM [cte_select_6] AS L
    INNER JOIN [cte_formula_12] AS R
        ON L.[hostname] = R.[logged_hostname]
        AND L.[ops_varenummer] = R.[logged_varenummer]
),

[cte_filter_17] AS (
    SELECT *
    FROM [cte_join_4]
    WHERE [demo_url] != 1
),

[cte_filter_17_to_select_18] AS (
    SELECT
        [RecordID],
        [customerId],
        [UserSubject],
        [firstLevelLog],
        [rootLineString],
        [featureFlags],
        [myAccountId],
        [Date],
        [SchoolYear],
        [alter_varenummer] AS [ops_varenummer],
        [alter_hostname] AS [hostname],
        [timestamp],
        [mainUserGroup],
        [hashedUserid],
        [mainUserSubject],
        [queryParamsEncoded],
        [id],
        [isbn],
        [pageId],
        [companyId],
        [groupIds],
        [eKeysUser],
        [importFilename],
        [MainUserType],
        [PageViews],
        [*Unknown]
    FROM [cte_filter_17]
),

[cte_union_16] AS (
    -- UNION ALL preserves duplicates. Change to UNION to deduplicate.
    SELECT * FROM [cte_join_4]
    UNION ALL
    SELECT * FROM [cte_filter_17_to_select_18]
),

[cte_unique_19] AS (
    -- Unique anchor: first occurrence per key
    -- For duplicates anchor: change WHERE _rn = 1 to WHERE _rn > 1
    SELECT *
    FROM (
        SELECT
            *,
            ROW_NUMBER() OVER (
                PARTITION BY [RecordID]
                ORDER BY (SELECT NULL)
            ) AS _rn
        FROM [cte_union_16]
    ) AS _deduped
    WHERE _rn = 1
),

[cte_union_16_to_filter_69] AS (
    SELECT *
    FROM [cte_unique_19]
    WHERE [myAccountId] in ('STUDYBOXMYACCOUNT','MUNKSGAARDMYACCOUNT')
),

[cte_filter_80] AS (
    SELECT *
    FROM [cte_union_16_to_filter_69]
    WHERE [myAccountId] = 'SYSTIMEMYACCOUNT'
),

[cte_formula_84] AS (
    SELECT
        *,
        TitleCase([customerId]) AS [Publisher]
    FROM [cte_union_16_to_filter_69]
),

[cte_formula_53] AS (
    -- !!! STUB — requires manual review !!!
    SELECT
        *,
        NULL AS [Publisher]  -- TODO: -- LLM conversion failed: Unknown keyword arguments: `result_type`
    FROM [cte_union_16_to_filter_69]
),

[cte_summarize_39] AS (
    SELECT
        [isbn],
        [companyId],
        [customerId],
        [UserSubject],
        [Date],
        [SchoolYear],
        [ops_varenummer],
        [hostname],
        [MainUserType],
        [myAccountId],
        SUM([PageViews]) AS [Sum_PageViews]
    FROM [cte_filter_80]
    GROUP BY [isbn], [companyId], [customerId], [UserSubject], [Date], [SchoolYear], [ops_varenummer], [hostname], [MainUserType], [myAccountId]
),

[cte_join_72] AS (
    -- Join anchor output (matched rows)
    -- Left-only:  add WHERE R.[eKeysUser] IS NULL
    -- Right-only: add WHERE L.[ekeys_userid] IS NULL
    SELECT
        L.*,
        R.*
    FROM [cte_formula_84] AS L
    INNER JOIN [cte_select_89] AS R
        ON L.[ekeys_userid] = R.[eKeysUser]
),

[cte_filter_70] AS (
    SELECT *
    FROM [cte_formula_53]
    WHERE [Publisher] != 'Other StudyBox'
),

[cte_formula_81] AS (
    SELECT
        *,
        TitleCase([customerId]) AS [Publisher]
    FROM [cte_summarize_39]
),

[cte_union_79] AS (
    SELECT *
    FROM [cte_join_72]
),

[cte_record_id_46] AS (
    SELECT
        *,
        ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS [RecordID]
    FROM [cte_formula_81]
),

[cte_summarize_74] AS (
    SELECT
        [isbn],
        [companyId],
        [CompanyName],
        [CompanyCountry],
        [CompanyZipCity],
        [CompanyAddress],
        [customerId],
        [UserSubject],
        [Date],
        [SchoolYear],
        [ops_varenummer],
        [hostname],
        [MainUserType],
        [myAccountId],
        SUM([pageViews]) AS [Sum_pageViews],
        [Publisher]
    FROM [cte_union_79]
    GROUP BY [isbn], [companyId], [CompanyName], [CompanyCountry], [CompanyZipCity], [CompanyAddress], [customerId], [UserSubject], [Date], [SchoolYear], [ops_varenummer], [hostname], [MainUserType], [myAccountId], [Publisher]
),

[cte_join_3] AS (
    -- Join anchor output (matched rows)
    -- Left-only:  add WHERE R.[MainItemNumber] IS NULL
    -- Right-only: add WHERE L.[ops_varenummer] IS NULL
    SELECT
        L.*,
        R.*
    FROM [cte_select_36] AS L
    INNER JOIN [cte_record_id_46] AS R
        ON L.[ops_varenummer] = R.[MainItemNumber]
),

[cte_record_id_76] AS (
    SELECT
        *,
        ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS [RecordID]
    FROM [cte_summarize_74]
),

[cte_select_51] AS (
    SELECT
        [companyId],
        [*Unknown]
    FROM [cte_join_3]
),

[cte_join_75] AS (
    -- Join anchor output (matched rows)
    -- Left-only:  add WHERE R.[MainItemNumber] IS NULL
    -- Right-only: add WHERE L.[ops_varenummer] IS NULL
    SELECT
        L.*,
        R.*
    FROM [cte_select_36] AS L
    INNER JOIN [cte_record_id_76] AS R
        ON L.[ops_varenummer] = R.[MainItemNumber]
),

[cte_join_32] AS (
    -- Join anchor output (matched rows)
    -- Left-only:  add WHERE R.[CompanyID] IS NULL
    -- Right-only: add WHERE L.[companyId] IS NULL
    SELECT
        L.*,
        R.*
    FROM [cte_select_51] AS L
    INNER JOIN [cte_union_67] AS R
        ON L.[companyId] = R.[CompanyID]
),

[cte_unique_77] AS (
    -- Unique anchor: first occurrence per key
    -- For duplicates anchor: change WHERE _rn = 1 to WHERE _rn > 1
    SELECT *
    FROM (
        SELECT
            *,
            ROW_NUMBER() OVER (
                PARTITION BY [RecordID]
                ORDER BY (SELECT NULL)
            ) AS _rn
        FROM [cte_join_75]
    ) AS _deduped
    WHERE _rn = 1
),

[cte_union_65] AS (
    SELECT *
    FROM [cte_join_32]
),

[cte_union_65_to_unique_47] AS (
    -- Unique anchor: first occurrence per key
    -- For duplicates anchor: change WHERE _rn = 1 to WHERE _rn > 1
    SELECT *
    FROM (
        SELECT
            *,
            ROW_NUMBER() OVER (
                PARTITION BY [RecordID]
                ORDER BY (SELECT NULL)
            ) AS _rn
        FROM [cte_union_65]
    ) AS _deduped
    WHERE _rn = 1
),

[cte_union_78] AS (
    -- UNION ALL preserves duplicates. Change to UNION to deduplicate.
    SELECT * FROM [cte_union_65_to_unique_47]
    UNION ALL
    SELECT * FROM [cte_unique_77]
),

[cte_formula_85] AS (
    -- !!! STUB — requires manual review !!!
    SELECT
        *,
        NULL AS [Publisher_Final]  -- TODO: -- LLM conversion failed: Unknown keyword arguments: `result_type`
    FROM [cte_union_78]
),

[cte_formula_24] AS (
    SELECT
        *,
        [Engine.WorkflowFileName] AS [WorkflowName],
        [Engine.WorkflowDirectory] AS [WorkflowPath],
        GETDATE() AS [WorkflowLastUpdated]
    FROM [cte_formula_85]
),

[cte_select_48] AS (
    SELECT
        [Date],
        [SchoolYear],
        [Publisher_Final] AS [Publisher],
        [isbn],
        [MainItemNumber],
        [ItemNumber],
        [hostname],
        [PublicationName],
        [Unit],
        [Status],
        [ProjectManager],
        [LD],
        [CommunicationManager],
        [EditorInternal],
        [PublicationMainSubject],
        [companyId],
        [companyType],
        [CompanyName],
        [CompanyAddress],
        [CompanyZipCity],
        [CompanyCountry],
        [ParentCompanyID],
        [UserSubject],
        [MainUserType],
        [Sum_PageViews] AS [PageViews],
        [WorkflowName],
        [WorkflowPath],
        [WorkflowLastUpdated],
        [INV_DELIVERYDATE],
        [INV_ESTIMATEDDELIVERY],
        [INV_NEWRELEASESTART],
        [INV_NEWRELEASEEND],
        [myAccountId] AS [DistributionPlatform],
        [Team],
        [*Unknown]
    FROM [cte_formula_24]
),

[cte_macro_52] AS (
    -- !!! STUB — requires manual review !!!
    -- TODO: expand macro 'Cleanse.yxmc'
    -- Reads from: cte_select_48
    SELECT TOP 0 1 AS _macro_stub  -- replace with macro logic
),

[cte_union_78_to_db_file_output_49] AS (
    -- Output destination: [Aggregated_Daily_simple] (mode: Overwrite)
    -- Replace trailing SELECT with:
    --   INSERT INTO [Aggregated_Daily_simple] SELECT * FROM [cte_macro_52]
    SELECT * FROM [cte_macro_52]
)

SELECT * FROM [cte_union_78_to_db_file_output_49];
