"""Smoke tests for src/main.py CLI entry point."""

import subprocess
import sys
from pathlib import Path

EXAMPLE = Path(__file__).parent.parent / "examples" / "BI_Aggregate Daily Simple_LDB-01.yxmd"


def test_main_dry_run(tmp_path):
    """--dry-run prints the chunk table without writing any files."""
    result = subprocess.run(
        [sys.executable, "src/main.py", str(EXAMPLE), "--dry-run"],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, result.stderr
    assert "Parsed" in result.stdout
    assert "Chunked" in result.stdout
    assert "--dry-run" in result.stdout
    assert not list(tmp_path.glob("*.sql"))


def test_main_full_pipeline(tmp_path):
    """Full run writes a .sql and _docs.md file with expected content."""
    result = subprocess.run(
        [sys.executable, "src/main.py", str(EXAMPLE), "--output-dir", str(tmp_path)],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, result.stderr
    assert "SQL written to" in result.stdout
    assert "Docs written to" in result.stdout

    sql_files = list(tmp_path.glob("*.sql"))
    doc_files = list(tmp_path.glob("*_docs.md"))
    assert len(sql_files) == 1
    assert len(doc_files) == 1

    sql = sql_files[0].read_text()
    assert "WITH" in sql
    assert "Generated by alteryx-to-sql-agent" in sql
    assert "SELECT" in sql

    docs = doc_files[0].read_text()
    assert "## CTEs" in docs


def test_main_no_docs(tmp_path):
    """--no-docs writes only the .sql file, no _docs.md."""
    result = subprocess.run(
        [sys.executable, "src/main.py", str(EXAMPLE), "--output-dir", str(tmp_path), "--no-docs"],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, result.stderr
    assert "SQL written to" in result.stdout
    assert "Docs written to" not in result.stdout

    sql_files = list(tmp_path.glob("*.sql"))
    doc_files = list(tmp_path.glob("*_docs.md"))
    assert len(sql_files) == 1
    assert len(doc_files) == 0


def test_main_missing_file():
    """A missing workflow file exits with code 1."""
    result = subprocess.run(
        [sys.executable, "src/main.py", "nonexistent.yxmd"],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 1
    assert "ERROR" in result.stdout or "ERROR" in result.stderr
