-- =============================================================================
-- Generated by alteryx-to-sql-agent
-- Source:    BI_Aggregate Daily Simple_LDB-01.yxmd
-- Generated: 2026-04-16 08:52:04 UTC
-- Stubs:     34 CTE(s) require manual review
-- =============================================================================

CREATE PROCEDURE [dbo].[BI_Aggregate_Daily_Simple_LDB_01]
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @WorkflowDirectory NVARCHAR(255) = N'<replace me>';
    DECLARE @WorkflowFileName NVARCHAR(255) = N'<replace me>';

    WITH
    -- -----------------------------------------------------------------------------
    -- SOURCE LOADING
    -- -----------------------------------------------------------------------------
    
    [cte_db_file_input_2] AS (
        -- !!! STUB — requires manual review !!!
        SELECT
            [ITEMNUMBER],
            [INV_MAINITEM],
            [ISBN13],
            [ITEMNAME1],
            [ITEMNAME2],
            [ITEMNAME3],
            [ITEMTYPE],
            [UNITCODE],
            [INV_PUBLICATIONSTATUS],
            [ENUMTXT_Publicationstatus],
            [INV_FORLAG],
            [ENUMTXT_Forlag],
            [INV_REDINTERN],
            [PROJLEADER],
            [PRODLEADER],
            [COMMANAGER],
            [GROUP_],
            [GROUPNAME],
            [INV_DELIVERYDATE],
            [INV_ESTIMATEDDELIVERY],
            [INV_NEWRELEASESTART],
            [INV_NEWRELEASEEND],
            [Team]
        FROM Publications
    ),
    
    [cte_text_input_14] AS (
        -- !!! STUB — requires manual review !!!
        SELECT [logged_varenummer], [logged_hostname], [alter_varenummer], [alter_hostname], [kommentar], [demo_url]
        FROM (VALUES
            (N'02321951', N'alverdensdanskbasis.ibog.gyldendal.dk', N'61683878', N'alverdensdanskbasis.ibog.gyldendal.dk', NULL, NULL),
            (N'61683878', N'alverdensdanskbasis.systime.dk', N'61683878', N'alverdensdanskbasis.ibog.gyldendal.dk', NULL, NULL),
            (N'61685377', N'alverdensdanskd.systime.dk', N'61685377', N'alverdensdanskd.ibog.gyldendal.dk', NULL, NULL),
            (N'61685360', N'alverdensdanske.systime.dk', N'61685360', N'alverdensdanske.ibog.gyldendal.dk', NULL, NULL),
            (N'61685353', N'alverdensdanskf.systime.dk', N'61685353', N'alverdensdanskf.ibog.gyldendal.dk', NULL, NULL),
            (N'61685346', N'alverdensdanskg.systime.dk', N'61685346', N'alverdensdanskg.ibog.gyldendal.dk', NULL, NULL),
            (N'61617699', N'aqueno.systime.dk', N'None', N'aqueno.systime.dk', N'website', N'1'),
            (N'61613004', N'aquesi.systime.dk', N'None', N'aquesi.systime.dk', N'Website', N'1'),
            (N'61647405', N'avusamf.systime.dk', N'61647405', N'avusamf.ibog.gyldendal.dk', NULL, NULL),
            (N'61658364', N'avusamfd.systime.dk', N'61658364', N'avusamfd.ibog.gyldendal.dk', NULL, NULL),
            (N'61656513', N'berlinerleben.systime.dk', N'61656513', N'berlinerleben.ibog.gyldendal.dk', NULL, NULL),
            (N'93647084', N'biofakta.ibog.nucleus.dk', N'90364708', N'biofakta.ibog.nucleus.dk', NULL, N'0'),
            (N'61697226', N'blackvoices.ibog.gyldendal.dk', N'02296273', N'blackvoices.systime.dk', NULL, N'0'),
            (N'61695437', N'danskfgu.systime.dk', N'61695437', N'danskfgu.ibog.gyldendal.dk', NULL, NULL),
            (N'61643650', N'dbd.systime.dk', N'61643650', N'dbd.ibog.gyldendal.dk', NULL, NULL),
            (N'61617545', N'debut2.systime.dk', N'61696069', N'debut2.systime.dk', N'website', N'1'),
            (N'61687258', N'engelskbasistilg.systime.dk', N'61687258', N'engelskbasistilg.ibog.gyldendal.dk', NULL, NULL),
            (N'61695758', N'engelskfgu.systime.dk', N'61695758', N'engelskfgu.ibog.gyldendal.dk', NULL, NULL),
            (N'MISSING', N'engelskstartgrammatik2.systime.dk', N'61697288', N'engelskstartgrammatik2.systime.dk', NULL, N'0'),
            (N'00000000', N'euddansk.ibog.gyldendal.dk', N'62820890', N'euddansk.ibog.gyldendal.dk', NULL, N'0'),
            (N'61699435', N'forbudtlitteratur.systime.dk', N'61698711', N'forbudtlitteratur.systime.dk', NULL, N'0'),
            (N'00000000', N'gerontologi-perspektiverpaaaeldre.ibog.studybox.dk', N'12063162', N'gerontologi-perspektiverpaaaeldre.ibog.studybox.dk', NULL, N'0'),
            (N'61686671', N'grundlaeggendeit.systime.dk', N'61686671', N'grundlaeggendeit.ibog.gyldendal.dk', NULL, NULL),
            (N'61698285', N'handelogkundeservice.systime.dk', N'61698285', N'handelogkundeservice.ibog.gyldendal.dk', NULL, NULL),
            (N'62509511', N'hardustyrpaadinfysik.ibog.gyldendal.dk', N'02306903', N'hardustyrpaadinfysik.systime.dk', NULL, N'0'),
            (N'61695178', N'imfgu.systime.dk', N'61695178', N'imfgu.ibog.gyldendal.dk', NULL, NULL),
            (N'61636997', N'isamf.systime.dk', N'61684103', N'isamf.systime.dk', NULL, NULL),
            (N'61614155', N'kinesisk1.systime.dk', N'61614157', N'kinesisk1.systime.dk', N'Website', N'1'),
            (N'61686893', N'komimaalmedskrivningd.systime.dk', N'61686893', N'komimaalmedskrivningd.ibog.gyldendal.dk', NULL, NULL),
            (N'61684288', N'komimaalmedskrivningg.systime.dk', N'61684288', N'komimaalmedskrivningg.ibog.gyldendal.dk', NULL, NULL),
            (N'00000000', N'kommunikationforsundhedsprofessionelle.ibog.studybox.dk', N'12063216', N'kommunikationforsundhedsprofessionelle.ibog.studybox.dk', NULL, N'0'),
            (N'MISSING', N'kommunikationogit.systime.dk', N'61671820', N'kommunikationogit.systime.dk', NULL, N'0'),
            (N'61693075', N'laerdanskmedtvserier.systime.dk', N'61693075', N'laerdanskmedtvserier.ibog.gyldendal.dk', NULL, NULL),
            (N'61670021', N'lmsm.systime.dk', N'61670021', N'lmsm.ibog.gyldendal.dk', NULL, NULL),
            (N'61671837', N'mat123.systime.dk', N'61671837', N'mat123.ibog.gyldendal.dk', NULL, NULL),
            (N'61686602', N'morfemer.systime.dk', N'61686602', N'morfemer.ibog.gyldendal.dk', NULL, NULL),
            (N'61693716', N'naturfagfgu.systime.dk', N'61693716', N'naturfagfgu.ibog.gyldendal.dk', NULL, NULL),
            (N'61670939', N'naturvidenskabavu.systime.dk', N'61670939', N'naturvidenskabavu.ibog.gyldendal.dk', NULL, NULL),
            (N'61617057', N'noegletilmusikken.systime.dk', N'61617059', N'noegletilmusikken.systime.dk', NULL, N'0'),
            (N'MISSING', N'oktober1943.systime.dk', N'61661708', N'oktober1943.systime.dk', NULL, N'0'),
            (N'61695109', N'pasefgu.systime.dk', N'61695109', N'pasefgu.ibog.gyldendal.dk', NULL, NULL),
            (N'00000000', N'patientinddragelseipraksis.ibog.studybox.dk', N'12063308', N'patientinddragelseipraksis.ibog.studybox.dk', NULL, N'0'),
            (N'61693709', N'plusfgu.systime.dk', N'61693709', N'plusfgu.ibog.gyldendal.dk', NULL, NULL),
            (N'61645210', N'plusfrabasistild.systime.dk', N'61645210', N'plusfrabasistild.ibog.gyldendal.dk', NULL, NULL),
            (N'00000000', N'praksisfaellesskaber.ibog.studybox.dk', N'41279107', N'praksisfaellesskaber.ibog.studybox.dk', NULL, N'0'),
            (N'00000000', N'projektledelseisundhedsvaesnet.ibog.studybox.dk', N'12063339', N'projektledelseisundhedsvaesnet.ibog.studybox.dk', NULL, N'0'),
            (N'61649911', N'relations.systime.dk', N'61649911', N'relations.ibog.gyldendal.dk', NULL, NULL),
            (N'61651259', N'rodisproget.systime.dk', N'61651259', N'rodisproget.ibog.gyldendal.dk', NULL, NULL),
            (N'61694911', N'samarbejdeogkommunikation.systime.dk', N'61694911', N'samarbejdeogkommunikation.ibog.gyldendal.dk', NULL, NULL),
            (N'61695147', N'samfundsfagfgu.systime.dk', N'61695147', N'samfundsfagfgu.ibog.gyldendal.dk', NULL, NULL),
            (N'MISSING', N'silamiut.systime.dk', N'93181144', N'silamiut.systime.dk', NULL, N'0'),
            (N'61666376', N'skriveoevelsertildansk.systime.dk', N'61666376', N'skriveoevelsertildansk.ibog.gyldendal.dk', NULL, NULL),
            (N'00000000', N'sociologiforsundhedsprofessionelle.ibog.studybox.dk', N'12063377', N'sociologiforsundhedsprofessionelle.ibog.studybox.dk', NULL, N'0'),
            (N'61688279', N'sociologiskset.systime.dk', N'61631022', N'sociologiskset.systime.dk', N'URL har logget flere varenumre. Varenummer ændres til til det, der skal afregnes på.', N'0'),
            (N'61698292', N'sprogligmatematik.systime.dk', N'61698292', N'sprogligmatematik.ibog.gyldendal.dk', NULL, NULL),
            (N'62819504', N'ssa-sammenhaeng.ibog.gyldendal.dk', N'62820302', N'ssa-sammenhaeng.ibog.gyldendal.dk', NULL, N'1'),
            (N'62818330', N'ssh-sundhedsfremme.ibog.gyldendal.dk', N'62820210', N'ssh-sundhedsfremme.ibog.gyldendal.dk', NULL, N'0'),
            (N'00000000', N'sygdomslaere-menneskekroppen.ibog.studybox.dk', N'12062943', N'sygdomslaere-menneskekroppen.ibog.studybox.dk', NULL, N'0'),
            (N'61695338', N'teknologiforstaaelsefgu.systime.dk', N'61695338', N'teknologiforstaaelsefgu.ibog.gyldendal.dk', NULL, NULL),
            (N'61668233', N'tg.systime.dk', N'61668233', N'tg.ibog.gyldendal.dk', NULL, NULL),
            (N'61691798', N'traendansk.systime.dk', N'61691798', N'traendansk.ibog.gyldendal.dk', NULL, NULL),
            (N'61660640', N'tyskbasis.systime.dk', N'61660640', N'tyskbasis.ibog.gyldendal.dk', NULL, NULL),
            (N'02290141', N'allesinallem.ibog.gyldendal.dk', N'02290141', N'allesinallem.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02314496', N'angles.ibog.gyldendal.dk', N'02314496', N'angles.ibog.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02290370', N'apbogen.ibog.gyldendal.dk', N'02290370', N'apbogen.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'62511811', N'aufuns.ibog.gyldendal.dk', N'62511811', N'aufuns.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02290080', N'basalvidenskabsteori.ibog.gyldendal.dk', N'02290080', N'basalvidenskabsteori.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'62513303', N'beingamerican.ibog.gyldendal.dk', N'62513303', N'beingamerican.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02301564', N'bforbedreidraet.ibog.gyldendal.dk', N'02301564', N'bforbedreidraet.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02296273', N'blackvoices.ibog.gyldendal.dk', N'02296273', N'blackvoices.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02290752', N'caminando.ibog.gyldendal.dk', N'02290752', N'caminando.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02290387', N'caminandoforfortsaettere.ibog.gyldendal.dk', N'02290387', N'caminandoforfortsaettere.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02292589', N'closeup.ibog.gyldendal.dk', N'02292589', N'closeup.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02290097', N'demokratimagtogpolitik.ibog.gyldendal.dk', N'02290097', N'demokratimagtogpolitik.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02290356', N'deneuropaeiskekoncert.ibog.gyldendal.dk', N'02290356', N'deneuropaeiskekoncert.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'62516571', N'detmodernegennembrud.ibog.gyldendal.dk', N'62516571', N'detmodernegennembrud.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02296815', N'dho-skriveguide.ibog.gyldendal.dk', N'02296815', N'dho-skriveguide.ibog.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'62516212', N'digogdigitaldannelseidansk.ibog.gyldendal.dk', N'62516212', N'digogdigitaldannelseidansk.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02290073', N'dinidraetc.ibog.gyldendal.dk', N'02290073', N'dinidraetc.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'62516748', N'einszweidrei.ibog.gyldendal.dk', N'62516748', N'einszweidrei.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02290363', N'eneuropaeiskverdenshistorie.ibog.gyldendal.dk', N'02290363', N'eneuropaeiskverdenshistorie.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'62507968', N'engodhistorieomreligion.ibog.gyldendal.dk', N'62507968', N'engodhistorieomreligion.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02301571', N'enverdenaffysika.ibog.gyldendal.dk', N'02301571', N'enverdenaffysika.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02290226', N'enverdenaffysikb.ibog.gyldendal.dk', N'02290226', N'enverdenaffysikb.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02290646', N'enverdenaffysikc.ibog.gyldendal.dk', N'02290646', N'enverdenaffysikc.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02308709', N'espanaenlacalle.ibog.gyldendal.dk', N'02308709', N'espanaenlacalle.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'62512061', N'filmskalsesidansk.ibog.gyldendal.dk', N'62512061', N'filmskalsesidansk.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'62511996', N'folkevisen.ibog.gyldendal.dk', N'62511996', N'folkevisen.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02290325', N'footprints.ibog.gyldendal.dk', N'02290325', N'footprints.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02306613', N'forloebtilhistorie1.ibog.gyldendal.dk', N'02306613', N'forloebtilhistorie1.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02306637', N'forloebtilhistorie2.ibog.gyldendal.dk', N'02306637', N'forloebtilhistorie2.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02306644', N'forloebtilhistorie3.ibog.gyldendal.dk', N'02306644', N'forloebtilhistorie3.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02290134', N'fortaellingensspejl.ibog.gyldendal.dk', N'02290134', N'fortaellingensspejl.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'62516281', N'fraantikkentileuropaeiskekspansion.ibog.gyldendal.dk', N'62516281', N'fraantikkentileuropaeiskekspansion.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02290400', N'fraidetilvirkelighed.ibog.gyldendal.dk', N'02290400', N'fraidetilvirkelighed.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'62516298', N'fraoplysningstidtileuropaeiskintegration.ibog.gyldendal.dk', N'62516298', N'fraoplysningstidtileuropaeiskintegration.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'62511774', N'gattungen.ibog.gyldendal.dk', N'62511774', N'gattungen.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'62515314', N'genau.ibog.gyldendal.dk', N'62515314', N'genau.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02296280', N'getitright.ibog.gyldendal.dk', N'02296280', N'getitright.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02290332', N'gettingstarted.ibog.gyldendal.dk', N'02290332', N'gettingstarted.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02320732', N'gettingstarteda.ibog.gyldendal.dk', N'02320732', N'gettingstarteda.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02300642', N'godespoergsmaalrigtigesvar.ibog.gyldendal.dk', N'02300642', N'godespoergsmaalrigtigesvar.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02290110', N'grundbogibioteknologi1htx.ibog.gyldendal.dk', N'02290110', N'grundbogibioteknologi1htx.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02290103', N'grundbogibioteknologi1stx.ibog.gyldendal.dk', N'02290103', N'grundbogibioteknologi1stx.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02293180', N'grundbogibioteknologi2htx.ibog.gyldendal.dk', N'02293180', N'grundbogibioteknologi2htx.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02293166', N'grundbogibioteknologi2stx.ibog.gyldendal.dk', N'02293166', N'grundbogibioteknologi2stx.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02290059', N'grundbogiidraetc.ibog.gyldendal.dk', N'02290059', N'grundbogiidraetc.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02290721', N'grundbogisamfundsfagc.ibog.gyldendal.dk', N'02290721', N'grundbogisamfundsfagc.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02301526', N'grundlaeggendefysika.ibog.gyldendal.dk', N'02301526', N'grundlaeggendefysika.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02290233', N'grundlaeggendefysikb.ibog.gyldendal.dk', N'02290233', N'grundlaeggendefysikb.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02306927', N'gyldendalsidraetspsykologi.ibog.gyldendal.dk', N'02306927', N'gyldendalsidraetspsykologi.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02290653', N'gymnasiematematika1.ibog.gyldendal.dk', N'02290653', N'gymnasiematematika1.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02290240', N'gymnasiematematika2.ibog.gyldendal.dk', N'02290240', N'gymnasiematematika2.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'62516724', N'gymnasiematematika3.ibog.gyldendal.dk', N'62516724', N'gymnasiematematika3.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02290660', N'gymnasiematematikb1.ibog.gyldendal.dk', N'02290660', N'gymnasiematematikb1.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02290257', N'gymnasiematematikb2.ibog.gyldendal.dk', N'02290257', N'gymnasiematematikb2.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02292947', N'gymnasiematematikbtila.ibog.gyldendal.dk', N'02292947', N'gymnasiematematikbtila.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02290066', N'gymnasiematematikg.ibog.gyldendal.dk', N'02290066', N'gymnasiematematikg.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02306903', N'hardustyrpaadinfysik.ibog.gyldendal.dk', N'02306903', N'hardustyrpaadinfysik.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02306897', N'hardustyrpaadinmatematik.ibog.gyldendal.dk', N'02306897', N'hardustyrpaadinmatematik.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02306910', N'huskhjernen.ibog.gyldendal.dk', N'02306910', N'huskhjernen.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'62516786', N'idehistoriehtx.ibog.gyldendal.dk', N'62516786', N'idehistoriehtx.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02290264', N'ifysikc.ibog.gyldendal.dk', N'02290264', N'ifysikc.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02290271', N'ifysikcb.ibog.gyldendal.dk', N'02290271', N'ifysikcb.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02291056', N'jamesjoyce.ibog.gyldendal.dk', N'02291056', N'jamesjoyce.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02290288', N'kendkemien1.ibog.gyldendal.dk', N'02290288', N'kendkemien1.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02290318', N'kendkemien2.ibog.gyldendal.dk', N'02290318', N'kendkemien2.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02321333', N'kendkemien3.ibog.gyldendal.dk', N'02321333', N'kendkemien3.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02321272', N'kritisktaenkning.ibog.gyldendal.dk', N'02321272', N'kritisktaenkning.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'62515222', N'krydsfelt.ibog.gyldendal.dk', N'62515222', N'krydsfelt.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02290776', N'laidentidadcontrastada.ibog.gyldendal.dk', N'02290776', N'laidentidadcontrastada.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'62515130', N'losgehts.ibog.gyldendal.dk', N'62515130', N'losgehts.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02298000', N'medtiden.ibog.gyldendal.dk', N'02298000', N'medtiden.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02291025', N'modernmetropolis.ibog.gyldendal.dk', N'02291025', N'modernmetropolis.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'62512160', N'mundtligeksamenidansk.ibog.gyldendal.dk', N'62512160', N'mundtligeksamenidansk.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02303292', N'naturvidenskabensverden.ibog.gyldendal.dk', N'02303292', N'naturvidenskabensverden.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02299717', N'paasporetafhistorien.ibog.gyldendal.dk', N'02299717', N'paasporetafhistorien.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'62511422', N'refleksion.ibog.gyldendal.dk', N'62511422', N'refleksion.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02291049', N'rusland.ibog.gyldendal.dk', N'02291049', N'rusland.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'62518186', N'skriftligeksamenidansk.ibog.gyldendal.dk', N'62518186', N'skriftligeksamenidansk.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02305159', N'skriftligeksamenidanskhhx.ibog.gyldendal.dk', N'02305159', N'skriftligeksamenidanskhhx.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02305166', N'skriftligeksamenidanskhtx.ibog.gyldendal.dk', N'02305166', N'skriftligeksamenidanskhtx.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02305906', N'skriftligeksameniengelskhhx.ibog.gyldendal.dk', N'02305906', N'skriftligeksameniengelskhhx.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02290684', N'skriftligeksameniengelskstxoghf.ibog.gyldendal.dk', N'02290684', N'skriftligeksameniengelskstxoghf.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'62515710', N'sociologi.ibog.gyldendal.dk', N'62515710', N'sociologi.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02290349', N'sprogenesverden.ibog.gyldendal.dk', N'02290349', N'sprogenesverden.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02297485', N'sprogpaaspil.ibog.gyldendal.dk', N'02297485', N'sprogpaaspil.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'62515512', N'sturmerunddranger.ibog.gyldendal.dk', N'62515512', N'sturmerunddranger.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02303285', N'tapasonline.ibog.gyldendal.dk', N'02303285', N'tapasonline.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02317770', N'tekster-foer-1700tallet.ibog.gyldendal.dk', N'02317770', N'tekster-foer-1700tallet.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'62509559', N'thegothicuniverse.ibog.gyldendal.dk', N'62509559', N'thegothicuniverse.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02292886', N'toolbox.ibog.gyldendal.dk', N'02292886', N'toolbox.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02290394', N'undeuxtrois.ibog.gyldendal.dk', N'02290394', N'undeuxtrois.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02290769', N'unodostres.ibog.gyldendal.dk', N'02290769', N'unodostres.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02293395', N'vaerklaesningthehateugive.ibog.gyldendal.dk', N'02293395', N'vaerklaesningthehateugive.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02291063', N'victorianwomenmenandmarriage.ibog.gyldendal.dk', N'02291063', N'victorianwomenmenandmarriage.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02308716', N'voila.ibog.gyldendal.dk', N'02308716', N'voila.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'62518087', N'werbinich.ibog.gyldendal.dk', N'62518087', N'werbinich.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'62514324', N'widercontexts.ibog.gyldendal.dk', N'62514324', N'widercontexts.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02290219', N'wiegehts.ibog.gyldendal.dk', N'02290219', N'wiegehts.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0'),
            (N'02290691', N'writeon.ibog.gyldendal.dk', N'02290691', N'writeon.systime.dk', N'Urlskiift ifm. overflytning fra Gyl til Sys', N'0')
        ) AS _t ([logged_varenummer], [logged_hostname], [alter_varenummer], [alter_hostname], [kommentar], [demo_url])
    ),
    
    [cte_db_file_input_29] AS (
        -- !!! STUB — requires manual review !!!
        SELECT
            [DATASET],
            [ROWNUMBER],
            [LASTCHANGED],
            [DEL_USERLOCK],
            [ACCOUNT],
            [NAME],
            [ADDRESS1],
            [ADDRESS2],
            [ZIPCITY],
            [COUNTRY],
            [ATTENTION],
            [PHONE],
            [FAX],
            [INVOICEACCOUNT],
            [GROUP_],
            [FIXEDDISCPCT],
            [APPROVED],
            [PRICEGROUP],
            [DISCGROUP],
            [CASHDISC],
            [IMAGEFILE],
            [CURRENCY],
            [LANGUAGE_],
            [PAYMENT],
            [DELIVERY],
            [BLOCKED],
            [SALESREP],
            [VAT],
            [DEL_STATTYPE],
            [GIRONUMBER],
            [VATNUMBER],
            [INTEREST],
            [DEPARTMENT],
            [REMINDERCODE],
            [ONETIMECUSTOMER],
            [INVENTORY],
            [EDIADDRESS],
            [BALANCE],
            [BALANCE30],
            [BALANCE60],
            [BALANCE90],
            [BALANCE120],
            [BALANCE120PLUS],
            [AMOUNTDUE],
            [CALCULATIONDATE],
            [BALANCEMAX],
            [BALANCEMST],
            [SEARCHNAME],
            [DEL_TRANSPORT],
            [CASHPAYMENT],
            [PAYMENTMODE],
            [SALESGROUP],
            [PROJGROUP],
            [TRADECODE],
            [TRANSPORTCODE],
            [EMAIL],
            [URL],
            [CELLPHONE],
            [KRAKNUMBER],
            [CENTRE],
            [PURPOSE],
            [EANNUMBER],
            [DIMACCOUNTCODE],
            [XMLINVOICE],
            [LASTINVOICEDATE],
            [LASTPAYMENTDATE],
            [LASTREMINDERDATE],
            [LASTINTERESTDATE],
            [LASTINVOICENUMBER],
            [XMLIMPORT],
            [VATGROUP],
            [STDACCOUNT],
            [VATNUMBERTYPE],
            [INV_UVMMAINNO],
            [INV_UVMGROUPNO],
            [INV_UVMNO],
            [INV_STATEMENTLETTER],
            [INV_BOGHNR],
            [POSTNR],
            [KUNDETYPE],
            [MINKONTO],
            [CRM],
            [FLATRATE],
            [DBA],
            [DBADATE],
            [DBACONTACT],
            [DBAEMAIL],
            [LASTIBOGDATO],
            [HOVEDEMAIL],
            [DELETE_TXT]
        FROM CUSTTABLE
    ),
    
    [cte_db_file_input_50] AS (
        -- !!! STUB — requires manual review !!!
        SELECT
            [hostname],
            [isbn],
            [companyId],
            [groupIds],
            [pageId],
            [mainUserGroup],
            [mainUserSubject],
            [firstLevelLog],
            [rootLineString],
            [featureFlags],
            [myAccountId],
            [queryParamsEncoded],
            [hashedUserid],
            [customerId],
            [timestamp],
            [id],
            [importFilename]
        FROM accounting
    ),
    
    [cte_text_input_66] AS (
        -- !!! STUB — requires manual review !!!
        SELECT [CompanyName], [CompanyAddress], [CompanyZipCity], [CompanyCountry], [ParentCompanyID], [companyType], [CompanyID]
        FROM (VALUES
            (N'Unknown', N'Unknown', N'0000', N'Unknown', NULL, N'vidr', N'0')
        ) AS _t ([CompanyName], [CompanyAddress], [CompanyZipCity], [CompanyCountry], [ParentCompanyID], [companyType], [CompanyID])
    ),
    
    [cte_db_file_input_71] AS (
        -- !!! STUB — requires manual review !!!
        SELECT
            [Eksternt sporings-id],
            [Rolle],
            [Studieretning],
            [Dato],
            [Institutionens ID],
            [Institutionens navn],
            [secret],
            [ekeys_userid],
            [CompanyAddress],
            [CompanyZipCity],
            [CompanyCountry],
            [WorkflowName],
            [WorkflowPath],
            [WorkflowLastUpdated]
        FROM StudyBoxUsers
    ),
    
    -- -----------------------------------------------------------------------------
    -- TRANSFORMATIONS
    -- -----------------------------------------------------------------------------
    
    [cte_select_36] AS (
        -- !!! STUB — requires manual review !!!
        SELECT
            [ITEMNUMBER] AS [ItemNumber],
            [INV_MAINITEM] AS [MainItemNumber],
            [ITEMNAME1] AS [PublicationName],
            [UNITCODE] AS [Unit],
            [ENUMTXT_Publicationstatus] AS [Status],
            [ENUMTXT_Forlag] AS [PublisherERP],
            [INV_REDINTERN] AS [EditorInternal],
            [PROJLEADER] AS [ProjectManager],
            [PRODLEADER] AS [LD],
            [COMMANAGER] AS [CommunicationManager],
            [GROUPNAME] AS [PublicationMainSubject],
            [ISBN13],
            [INV_DELIVERYDATE],
            [INV_ESTIMATEDDELIVERY],
            [INV_NEWRELEASESTART],
            [INV_NEWRELEASEEND],
            [Team]
        FROM [cte_db_file_input_2]
    ),
    
    [cte_select_6] AS (
        -- !!! STUB — requires manual review !!!
        SELECT
            [logged_varenummer],
            [alter_varenummer]
        FROM [cte_text_input_14]
    ),
    
    [cte_filter_30] AS (
        SELECT *
        FROM [cte_db_file_input_29]
        WHERE [DATASET] = 'DAT'
    ),
    
    [cte_select_86] AS (
        -- !!! STUB — requires manual review !!!
        SELECT
            [mainUserSubject] AS [UserSubject],
            [hashedUserid] AS [eKeysUser],
            [hostname],
            [isbn],
            [companyId],
            [groupIds],
            [pageId],
            [mainUserGroup],
            [firstLevelLog],
            [rootLineString],
            [featureFlags],
            [myAccountId],
            [queryParamsEncoded],
            [customerId],
            [timestamp],
            [id],
            [importFilename],
            [hashedUserid],
            [mainUserSubject]
        FROM [cte_db_file_input_50]
    ),
    
    [cte_select_89] AS (
        -- !!! STUB — requires manual review !!!
        SELECT
            [Studieretning] AS [UserSubject],
            [Dato] AS [CreatedDate],
            [Institutionens ID] AS [companyId],
            [Institutionens navn] AS [CompanyName],
            [Eksternt sporings-id],
            [Rolle],
            [secret],
            [ekeys_userid],
            [CompanyAddress],
            [CompanyZipCity],
            [CompanyCountry],
            [WorkflowName],
            [WorkflowPath],
            [WorkflowLastUpdated]
        FROM [cte_db_file_input_71]
    ),
    
    [cte_macro_31] AS (
        -- !!! STUB — requires manual review !!!
        -- TODO: expand macro 'Cleanse.yxmc'
        -- Reads from: cte_filter_30
        SELECT TOP 0 1 AS _macro_stub  -- replace with macro logic
    ),
    
    [cte_formula_38] AS (
        -- !!! STUB — requires manual review !!!
        SELECT
            *,
            CASE WHEN MONTH([timestamp]) > 7 THEN CAST(YEAR([timestamp]) AS VARCHAR(4)) + '/' + CAST(YEAR([timestamp]) + 1 AS VARCHAR(4)) ELSE CAST(YEAR([timestamp]) - 1 AS VARCHAR(4)) + '/' + CAST(YEAR([timestamp]) AS VARCHAR(4)) END AS [SchoolYear],
            CAST([timestamp] AS DATE) AS [Date]
        FROM [cte_select_86]
    ),
    
    [cte_filter_45] AS (
        -- !!! STUB — requires manual review !!!
        SELECT *
        FROM [cte_macro_31]
        WHERE TRY_CAST([ACCOUNT] AS INT) IS NOT NULL
    ),
    
    [cte_formula_87] AS (
        -- !!! STUB — requires manual review !!!
        SELECT
            *,
            CASE [mainUserGroup]
            WHEN '3' THEN 'Studerende'
            WHEN '21' THEN 'Valideret lærer'
            WHEN '2' THEN 'Lærere'
            WHEN '4' THEN 'Private'
            ELSE 'NA'
        END AS [MainUserType],
            1 AS [PageViews]
        FROM [cte_formula_38]
    ),
    
    [cte_formula_43] AS (
        -- !!! STUB — requires manual review !!!
        SELECT
            *,
            TRY_CAST([ACCOUNT] AS FLOAT) AS [CompanyID]
        FROM [cte_filter_45]
    ),
    
    [cte_formula_15] AS (
        -- !!! STUB — requires manual review !!!
        SELECT
            *,
            CASE WHEN [isbn] = 'MISSING' THEN [isbn] ELSE RIGHT([isbn], 8) END AS [ops_varenummer]
        FROM [cte_formula_87]
    ),
    
    [cte_select_44] AS (
        -- !!! STUB — requires manual review !!!
        SELECT
            [NAME] AS [CompanyName],
            [ADDRESS1] AS [CompanyAddress],
            [ZIPCITY] AS [CompanyZipCity],
            [COUNTRY] AS [CompanyCountry],
            [INVOICEACCOUNT] AS [ParentCompanyID],
            [GROUP_] AS [companyType],
            [CompanyID]
        FROM [cte_formula_43]
    ),
    
    [cte_record_id_20] AS (
        -- !!! STUB — requires manual review !!!
        SELECT
            *,
            ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS [RecordID]
        FROM [cte_formula_15]
    ),
    
    [cte_union_67] AS (
        -- UNION ALL preserves duplicates. Change to UNION to deduplicate.
        SELECT * FROM [cte_select_44]
        UNION ALL
        SELECT * FROM [cte_text_input_66]
    ),
    
    [cte_formula_12] AS (
        SELECT
            *,
            CASE 
            WHEN [UserSubject] IN ('eud/eux', 'eud/eux/kuu') THEN 'eud/eux'
            WHEN [UserSubject] IN ('Andet', 'N/A', 'Not set') THEN 'Andet'
            WHEN [UserSubject] = 'avu/fvu/obu/fgu' THEN 'avu/fvu/du/fgu'
            WHEN [UserSubject] IS NULL OR [UserSubject] = '' THEN 'Andet'
            ELSE [UserSubject]
        END AS [UserSubject]
        FROM [cte_record_id_20]
    ),
    
    [cte_join_4] AS (
        -- !!! STUB — requires manual review !!!
        -- Join anchor output (matched rows)
        -- Left-only:  add WHERE R.[logged_hostname] IS NULL
        -- Right-only: add WHERE L.[hostname] IS NULL
        SELECT
            L.[UserSubject],
            L.[eKeysUser],
            L.[hostname],
            L.[isbn],
            L.[companyId],
            L.[groupIds],
            L.[pageId],
            L.[mainUserGroup],
            L.[firstLevelLog],
            L.[rootLineString],
            L.[featureFlags],
            L.[myAccountId],
            L.[queryParamsEncoded],
            L.[customerId],
            L.[timestamp],
            L.[id],
            L.[importFilename],
            L.[SchoolYear],
            L.[Date],
            L.[MainUserType],
            L.[PageViews],
            L.[ops_varenummer],
            L.[RecordID],
            R.[logged_varenummer],
            R.[alter_varenummer],
            [hashedUserid],
            [mainUserSubject]
        FROM [cte_formula_12] AS L
        INNER JOIN [cte_select_6] AS R
            ON L.[hostname] = R.[logged_hostname]
            AND L.[ops_varenummer] = R.[logged_varenummer]
    ),
    
    [cte_filter_17] AS (
        -- !!! STUB — requires manual review !!!
        SELECT *
        FROM [cte_join_4]
        WHERE [demo_url] != 1
    ),
    
    [cte_filter_17_to_select_18] AS (
        -- !!! STUB — requires manual review !!!
        SELECT
            [RecordID],
            [customerId],
            [UserSubject],
            [firstLevelLog],
            [rootLineString],
            [featureFlags],
            [myAccountId],
            [Date],
            [SchoolYear],
            [alter_varenummer] AS [ops_varenummer],
            [alter_hostname] AS [hostname],
            [timestamp],
            [mainUserGroup],
            [hashedUserid],
            [mainUserSubject],
            [queryParamsEncoded],
            [id],
            [isbn],
            [pageId],
            [companyId],
            [groupIds],
            [eKeysUser],
            [importFilename],
            [MainUserType],
            [PageViews]
        FROM [cte_filter_17]
    ),
    
    [cte_union_16] AS (
        -- UNION ALL preserves duplicates. Change to UNION to deduplicate.
        SELECT * FROM [cte_filter_17_to_select_18]
        UNION ALL
        SELECT * FROM [cte_join_4]
    ),
    
    [cte_unique_19] AS (
        -- Unique anchor: first occurrence per key
        -- For duplicates anchor: change WHERE _rn = 1 to WHERE _rn > 1
        SELECT *
        FROM (
            SELECT
                *,
                ROW_NUMBER() OVER (
                    PARTITION BY [RecordID]
                    ORDER BY (SELECT NULL)
                ) AS _rn
            FROM [cte_union_16]
        ) AS _deduped
        WHERE _rn = 1
    ),
    
    [cte_union_16_to_filter_69] AS (
        SELECT *
        FROM [cte_unique_19]
        WHERE [myAccountId] in ('STUDYBOXMYACCOUNT','MUNKSGAARDMYACCOUNT')
    ),
    
    [cte_filter_80] AS (
        SELECT *
        FROM [cte_union_16_to_filter_69]
        WHERE [myAccountId] = 'SYSTIMEMYACCOUNT'
    ),
    
    [cte_formula_84] AS (
        -- !!! STUB — requires manual review !!!
        SELECT
            *,
            UPPER(LEFT([customerId], 1)) + LOWER(SUBSTRING([customerId], 2, LEN([customerId]))) AS [Publisher]
        FROM [cte_union_16_to_filter_69]
    ),
    
    [cte_formula_53] AS (
        -- !!! STUB — requires manual review !!!
        SELECT
            *,
            CASE 
            WHEN [myAccountId] = 'STUDYBOXMYACCOUNT' AND [customerId] IN ('Munksgaard', 'Hans Reitzel') THEN 'StudyBox'
            WHEN [myAccountId] = 'STUDYBOXMYACCOUNT' THEN 'Other StudyBox'
            ELSE [customerId] 
        END AS [Publisher]
        FROM [cte_union_16_to_filter_69]
    ),
    
    [cte_summarize_39] AS (
        -- !!! STUB — requires manual review !!!
        SELECT
            [isbn],
            [companyId],
            [customerId],
            [UserSubject],
            [Date],
            [SchoolYear],
            [ops_varenummer],
            [hostname],
            [MainUserType],
            [myAccountId],
            SUM([PageViews]) AS [Sum_PageViews],
            [PageViews]
        FROM [cte_filter_80]
        GROUP BY [isbn], [companyId], [customerId], [UserSubject], [Date], [SchoolYear], [ops_varenummer], [hostname], [MainUserType], [myAccountId]
    ),
    
    [cte_join_72] AS (
        -- !!! STUB — requires manual review !!!
        -- Join anchor output (matched rows)
        -- Left-only:  add WHERE R.[eKeysUser] IS NULL
        -- Right-only: add WHERE L.[ekeys_userid] IS NULL
        SELECT
            L.[UserSubject],
            L.[CreatedDate],
            L.[companyId],
            L.[CompanyName],
            L.[Eksternt sporings-id],
            L.[Rolle],
            L.[secret],
            L.[ekeys_userid],
            L.[CompanyAddress],
            L.[CompanyZipCity],
            L.[CompanyCountry],
            L.[WorkflowName],
            L.[WorkflowPath],
            L.[WorkflowLastUpdated],
            R.[RecordID],
            R.[customerId],
            R.[UserSubject] AS [Right_UserSubject],
            R.[firstLevelLog],
            R.[rootLineString],
            R.[featureFlags],
            R.[myAccountId],
            R.[Date],
            R.[SchoolYear],
            R.[ops_varenummer],
            R.[hostname],
            R.[timestamp],
            R.[mainUserGroup],
            R.[hashedUserid],
            R.[mainUserSubject],
            R.[queryParamsEncoded],
            R.[id],
            R.[isbn],
            R.[pageId],
            R.[companyId] AS [Right_companyId],
            R.[groupIds],
            R.[eKeysUser],
            R.[importFilename],
            R.[MainUserType],
            R.[PageViews],
            R.[Publisher]
        FROM [cte_select_89] AS L
        INNER JOIN [cte_formula_84] AS R
            ON L.[ekeys_userid] = R.[eKeysUser]
    ),
    
    -- -----------------------------------------------------------------------------
    -- OUTPUT
    -- -----------------------------------------------------------------------------
    
    [cte_filter_70] AS (
        SELECT *
        FROM [cte_formula_53]
        WHERE [Publisher] != 'Other StudyBox'
    ),
    
    -- -----------------------------------------------------------------------------
    -- TRANSFORMATIONS
    -- -----------------------------------------------------------------------------
    
    [cte_formula_81] AS (
        -- !!! STUB — requires manual review !!!
        SELECT
            *,
            UPPER(LEFT([customerId], 1)) + LOWER(SUBSTRING([customerId], 2, LEN([customerId]))) AS [Publisher]
        FROM [cte_summarize_39]
    ),
    
    [cte_union_79] AS (
        SELECT *
        FROM [cte_join_72]
    ),
    
    [cte_record_id_46] AS (
        -- !!! STUB — requires manual review !!!
        SELECT
            *,
            ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS [RecordID]
        FROM [cte_formula_81]
    ),
    
    [cte_summarize_74] AS (
        -- !!! STUB — requires manual review !!!
        SELECT
            [isbn],
            [companyId],
            [CompanyName],
            [CompanyCountry],
            [CompanyZipCity],
            [CompanyAddress],
            [customerId],
            [UserSubject],
            [Date],
            [SchoolYear],
            [ops_varenummer],
            [hostname],
            [MainUserType],
            [myAccountId],
            SUM([pageViews]) AS [Sum_pageViews],
            [Publisher]
        FROM [cte_union_79]
        GROUP BY [isbn], [companyId], [CompanyName], [CompanyCountry], [CompanyZipCity], [CompanyAddress], [customerId], [UserSubject], [Date], [SchoolYear], [ops_varenummer], [hostname], [MainUserType], [myAccountId], [Publisher]
    ),
    
    [cte_join_3] AS (
        -- Join anchor output (matched rows)
        -- Left-only:  add WHERE R.[MainItemNumber] IS NULL
        -- Right-only: add WHERE L.[ops_varenummer] IS NULL
        SELECT
            L.[isbn],
            L.[companyId],
            L.[customerId],
            L.[UserSubject],
            L.[Date],
            L.[SchoolYear],
            L.[ops_varenummer],
            L.[hostname],
            L.[MainUserType],
            L.[myAccountId],
            L.[Sum_PageViews],
            L.[Publisher],
            L.[RecordID],
            R.[ItemNumber],
            R.[MainItemNumber],
            R.[PublicationName],
            R.[Unit],
            R.[Status],
            R.[PublisherERP],
            R.[EditorInternal],
            R.[ProjectManager],
            R.[LD],
            R.[CommunicationManager],
            R.[PublicationMainSubject],
            R.[ISBN13],
            R.[INV_DELIVERYDATE],
            R.[INV_ESTIMATEDDELIVERY],
            R.[INV_NEWRELEASESTART],
            R.[INV_NEWRELEASEEND],
            R.[Team],
            [PageViews]
        FROM [cte_record_id_46] AS L
        INNER JOIN [cte_select_36] AS R
            ON L.[ops_varenummer] = R.[MainItemNumber]
    ),
    
    [cte_record_id_76] AS (
        -- !!! STUB — requires manual review !!!
        SELECT
            *,
            ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS [RecordID]
        FROM [cte_summarize_74]
    ),
    
    [cte_select_51] AS (
        SELECT
            [companyId],
            [isbn],
            [customerId],
            [UserSubject],
            [Date],
            [SchoolYear],
            [ops_varenummer],
            [hostname],
            [MainUserType],
            [myAccountId],
            [Sum_PageViews],
            [Publisher],
            [RecordID],
            [ItemNumber],
            [MainItemNumber],
            [PublicationName],
            [Unit],
            [Status],
            [PublisherERP],
            [EditorInternal],
            [ProjectManager],
            [LD],
            [CommunicationManager],
            [PublicationMainSubject],
            [ISBN13],
            [INV_DELIVERYDATE],
            [INV_ESTIMATEDDELIVERY],
            [INV_NEWRELEASESTART],
            [INV_NEWRELEASEEND],
            [Team],
            [PageViews]
        FROM [cte_join_3]
    ),
    
    [cte_join_75] AS (
        -- Join anchor output (matched rows)
        -- Left-only:  add WHERE R.[MainItemNumber] IS NULL
        -- Right-only: add WHERE L.[ops_varenummer] IS NULL
        SELECT
            L.[isbn],
            L.[companyId],
            L.[CompanyName],
            L.[CompanyCountry],
            L.[CompanyZipCity],
            L.[CompanyAddress],
            L.[customerId],
            L.[UserSubject],
            L.[Date],
            L.[SchoolYear],
            L.[ops_varenummer],
            L.[hostname],
            L.[MainUserType],
            L.[myAccountId],
            L.[Sum_pageViews],
            L.[Publisher],
            L.[RecordID],
            R.[ItemNumber],
            R.[MainItemNumber],
            R.[PublicationName],
            R.[Unit],
            R.[Status],
            R.[PublisherERP],
            R.[EditorInternal],
            R.[ProjectManager],
            R.[LD],
            R.[CommunicationManager],
            R.[PublicationMainSubject],
            R.[ISBN13],
            R.[INV_DELIVERYDATE],
            R.[INV_ESTIMATEDDELIVERY],
            R.[INV_NEWRELEASESTART],
            R.[INV_NEWRELEASEEND],
            R.[Team]
        FROM [cte_record_id_76] AS L
        INNER JOIN [cte_select_36] AS R
            ON L.[ops_varenummer] = R.[MainItemNumber]
    ),
    
    [cte_join_32] AS (
        -- Join anchor output (matched rows)
        -- Left-only:  add WHERE R.[CompanyID] IS NULL
        -- Right-only: add WHERE L.[companyId] IS NULL
        SELECT
            L.[companyId],
            L.[isbn],
            L.[customerId],
            L.[UserSubject],
            L.[Date],
            L.[SchoolYear],
            L.[ops_varenummer],
            L.[hostname],
            L.[MainUserType],
            L.[myAccountId],
            L.[Sum_PageViews],
            L.[Publisher],
            L.[RecordID],
            L.[ItemNumber],
            L.[MainItemNumber],
            L.[PublicationName],
            L.[Unit],
            L.[Status],
            L.[PublisherERP],
            L.[EditorInternal],
            L.[ProjectManager],
            L.[LD],
            L.[CommunicationManager],
            L.[PublicationMainSubject],
            L.[ISBN13],
            L.[INV_DELIVERYDATE],
            L.[INV_ESTIMATEDDELIVERY],
            L.[INV_NEWRELEASESTART],
            L.[INV_NEWRELEASEEND],
            L.[Team],
            R.[CompanyName],
            R.[CompanyAddress],
            R.[CompanyZipCity],
            R.[CompanyCountry],
            R.[ParentCompanyID],
            R.[companyType],
            R.[CompanyID],
            [PageViews]
        FROM [cte_select_51] AS L
        INNER JOIN [cte_union_67] AS R
            ON L.[companyId] = R.[CompanyID]
    ),
    
    [cte_unique_77] AS (
        -- Unique anchor: first occurrence per key
        -- For duplicates anchor: change WHERE _rn = 1 to WHERE _rn > 1
        SELECT *
        FROM (
            SELECT
                *,
                ROW_NUMBER() OVER (
                    PARTITION BY [RecordID]
                    ORDER BY (SELECT NULL)
                ) AS _rn
            FROM [cte_join_75]
        ) AS _deduped
        WHERE _rn = 1
    ),
    
    [cte_union_65] AS (
        SELECT *
        FROM [cte_join_32]
    ),
    
    [cte_union_65_to_unique_47] AS (
        -- Unique anchor: first occurrence per key
        -- For duplicates anchor: change WHERE _rn = 1 to WHERE _rn > 1
        SELECT *
        FROM (
            SELECT
                *,
                ROW_NUMBER() OVER (
                    PARTITION BY [RecordID]
                    ORDER BY (SELECT NULL)
                ) AS _rn
            FROM [cte_union_65]
        ) AS _deduped
        WHERE _rn = 1
    ),
    
    [cte_union_78] AS (
        -- UNION ALL preserves duplicates. Change to UNION to deduplicate.
        SELECT
            [companyId],
            [isbn],
            [customerId],
            [UserSubject],
            [Date],
            [SchoolYear],
            [ops_varenummer],
            [hostname],
            [MainUserType],
            [myAccountId],
            [Sum_PageViews],
            [Publisher],
            [RecordID],
            [ItemNumber],
            [MainItemNumber],
            [PublicationName],
            [Unit],
            [Status],
            [PublisherERP],
            [EditorInternal],
            [ProjectManager],
            [LD],
            [CommunicationManager],
            [PublicationMainSubject],
            [ISBN13],
            [INV_DELIVERYDATE],
            [INV_ESTIMATEDDELIVERY],
            [INV_NEWRELEASESTART],
            [INV_NEWRELEASEEND],
            [Team],
            [CompanyName],
            [CompanyAddress],
            [CompanyZipCity],
            [CompanyCountry],
            [ParentCompanyID],
            [companyType],
            [CompanyID],
            NULL AS [Sum_pageViews],
            [PageViews]
        FROM [cte_union_65_to_unique_47]
        UNION ALL
        SELECT
            [companyId],
            [isbn],
            [customerId],
            [UserSubject],
            [Date],
            [SchoolYear],
            [ops_varenummer],
            [hostname],
            [MainUserType],
            [myAccountId],
            NULL AS [Sum_PageViews],
            [Publisher],
            [RecordID],
            [ItemNumber],
            [MainItemNumber],
            [PublicationName],
            [Unit],
            [Status],
            [PublisherERP],
            [EditorInternal],
            [ProjectManager],
            [LD],
            [CommunicationManager],
            [PublicationMainSubject],
            [ISBN13],
            [INV_DELIVERYDATE],
            [INV_ESTIMATEDDELIVERY],
            [INV_NEWRELEASESTART],
            [INV_NEWRELEASEEND],
            [Team],
            [CompanyName],
            [CompanyAddress],
            [CompanyZipCity],
            [CompanyCountry],
            NULL AS [ParentCompanyID],
            NULL AS [companyType],
            NULL AS [CompanyID],
            [Sum_pageViews]
        FROM [cte_unique_77]
    ),
    
    [cte_formula_85] AS (
        -- !!! STUB — requires manual review !!!
        SELECT
            *,
            CASE 
            WHEN [PublisherERP] = 'Dansklærerforeningen & Systime' AND [Publisher] = 'Systime' THEN 'Dansklærerforeningen & Systime'
            WHEN [PublisherERP] = 'Dansklærerforeningens Forlag' AND [Publisher] = 'Dlf' THEN 'Dansklærerforeningens Forlag'
            WHEN [PublisherERP] = 'DlfF Forlag' AND [Publisher] = 'Systime' THEN 'Systime'
            WHEN [PublisherERP] = 'FNAE' AND [Publisher] = 'Systime' THEN 'Systime'
            WHEN [PublisherERP] = 'Forlaget Columbus' AND [Publisher] = 'Columbus' THEN 'Forlaget Columbus'
            WHEN [PublisherERP] = 'GU Gym' AND [Publisher] = 'Gyldendal' THEN 'Gyldendal'
            WHEN [PublisherERP] = 'GU Sys' AND [Publisher] = 'Systime' THEN 'Systime'
            WHEN [PublisherERP] = 'Gyldendal' AND [Publisher] = 'Gyldendal-voksen' THEN 'Gyldendal'
            WHEN [PublisherERP] = 'Hans Reitzel' AND [Publisher] = 'Munksgaard' THEN 'Munksgaard'
            WHEN [PublisherERP] = 'Hans Reitzel' AND [Publisher] = 'Systime' THEN 'Systime'
            WHEN [PublisherERP] = 'Gyldendal' AND [Publisher] = 'Systime' THEN 'Systime'
            WHEN [PublisherERP] = 'Systime' AND [Publisher] = 'Systimesolutions' THEN 'Systimesolutions'
            WHEN [PublisherERP] = 'Systime/Hans Reitzel' AND [Publisher] = 'Hansreitzel' THEN 'Hans Reitzel'
            WHEN [PublisherERP] = 'Systime/Hans Reitzel' AND [Publisher] = 'Systime' THEN 'Systime'
            WHEN [PublisherERP] = 'GU Gym' THEN 'Gyldendal'
            WHEN [PublisherERP] = 'GU Sys' THEN 'Systime'
            WHEN [PublisherERP] = 'VIA-Systime' THEN 'Systime'
            WHEN [PublisherERP] = 'Kurlund' THEN 'Systime'
            WHEN [PublisherERP] = 'DlfF Forlag' THEN 'Dansklærerforeningen & Systime'
            ELSE [PublisherERP]
        END AS [Publisher_Final]
        FROM [cte_union_78]
    ),
    
    [cte_formula_24] AS (
        -- !!! STUB — requires manual review !!!
        SELECT
            *,
            @WorkflowFileName AS [WorkflowName],
            @WorkflowDirectory AS [WorkflowPath],
            GETDATE() AS [WorkflowLastUpdated]
        FROM [cte_formula_85]
    ),
    
    [cte_select_48] AS (
        -- !!! STUB — requires manual review !!!
        SELECT
            [Date],
            [SchoolYear],
            [Publisher_Final] AS [Publisher],
            [isbn],
            [MainItemNumber],
            [ItemNumber],
            [hostname],
            [PublicationName],
            [Unit],
            [Status],
            [ProjectManager],
            [LD],
            [CommunicationManager],
            [EditorInternal],
            [PublicationMainSubject],
            [companyId],
            [companyType],
            [CompanyName],
            [CompanyAddress],
            [CompanyZipCity],
            [CompanyCountry],
            [ParentCompanyID],
            [UserSubject],
            [MainUserType],
            [Sum_PageViews] AS [PageViews],
            [WorkflowName],
            [WorkflowPath],
            [WorkflowLastUpdated],
            [INV_DELIVERYDATE],
            [INV_ESTIMATEDDELIVERY],
            [INV_NEWRELEASESTART],
            [INV_NEWRELEASEEND],
            [myAccountId] AS [DistributionPlatform],
            [Team],
            [CompanyID]
        FROM [cte_formula_24]
    ),
    
    [cte_macro_52] AS (
        -- !!! STUB — requires manual review !!!
        -- TODO: expand macro 'Cleanse.yxmc'
        -- Reads from: cte_select_48
        SELECT TOP 0 1 AS _macro_stub  -- replace with macro logic
    ),
    
    -- -----------------------------------------------------------------------------
    -- OUTPUT
    -- -----------------------------------------------------------------------------
    
    [cte_union_78_to_db_file_output_49] AS (
        -- !!! STUB — requires manual review !!!
        -- Output destination: [Aggregated_Daily_simple] (mode: Overwrite)
        -- Replace trailing SELECT with:
        --   INSERT INTO [Aggregated_Daily_simple] SELECT * FROM [cte_macro_52]
        SELECT * FROM [cte_macro_52]
    )
    
    SELECT * FROM [cte_union_78_to_db_file_output_49];

END;
GO
