"""Column-reference validation and LLM repair pass.

After the deterministic liveness pass, some CTEs may still reference columns
that do not exist in any upstream schema.  Common causes:

  * LLM-hallucinated column names (e.g. ``[Sum_Pre]`` when only ``[Sum_reqs]``
    exists).
  * Columns that originate from a macro stub (schema unknown).
  * Cross-file CTE references generated by the LLM chunk translator.

For each broken CTE this module:
  1. Identifies which columns are missing from the input schemas.
  2. Sends the CTE body + schema context to the LLM repair agent.
  3. If the LLM returns a corrected body, updates the fragment SQL and sets
     ``llm_repaired=True``.  The CTE is still marked ``is_stub=True`` so
     reviewers know it was auto-corrected and should verify the result.
  4. If the LLM fails or is unavailable, falls back to the original stub with
     ``llm_repair_notes`` describing the missing columns.

Usage::

    from analysis.llm_validator import repair_fragments

    fragments = repair_fragments(fragments, ctx)
"""

from __future__ import annotations

import re

from llm.repair_agent import repair_cte_llm
from parsing.models import CTEFragment, FieldSchema
from translators.context import TranslationContext

_BRACKET_RE = re.compile(r"\[([^\]]+)\]")
_INTERNAL_COLS = {"_rn", "_stub", "_macro_stub", "_sort_order", "_deduped"}

# Strips "AS [alias]" so that alias names on the right side of a rename are not
# mistakenly treated as upstream column references.  Applied before bracket scanning.
_AS_ALIAS_RE = re.compile(r"\bAS\s+\[[^\]]+\]", re.IGNORECASE)

# Strips -- single-line comments so bracketed table names in comment text (e.g.
# "-- Output destination: [target_table]") are not treated as column references.
_COMMENT_RE = re.compile(r"--[^\n]*")


def _extract_col_refs(sql: str, known_ctes: set[str]) -> set[str]:
    sql_no_comments = _COMMENT_RE.sub("", sql)
    sql_no_aliases = _AS_ALIAS_RE.sub("", sql_no_comments)
    return {
        m.group(1)
        for m in _BRACKET_RE.finditer(sql_no_aliases)
        if m.group(1) and m.group(1) not in _INTERNAL_COLS and m.group(1) not in known_ctes
    }


def _schema_summary(name: str, schema: list[FieldSchema]) -> str:
    if not schema:
        return f"{name}: (schema unknown)"
    cols = ", ".join(f"[{f.name}]" for f in schema)
    return f"{name}: {cols}"


def repair_fragments(
    fragments: list[CTEFragment],
    ctx: TranslationContext,
) -> list[CTEFragment]:
    """Repair CTEs with unresolvable column references using the LLM.

    Non-stub CTEs are scanned for column references absent from their input
    schemas.  For each broken CTE the LLM repair agent is called; if it returns
    a corrected body the fragment SQL is updated and ``llm_repaired=True`` is
    set.  The CTE is still marked ``is_stub=True`` regardless, so reviewers
    know it was auto-corrected.  If the LLM fails, the original SQL is kept
    and only the diagnostic notes are added.

    Args:
        fragments: CTEFragment list (post liveness pass).
        ctx:       TranslationContext with populated ``cte_schema`` and
                   ``cte_inputs``.

    Returns:
        Updated fragment list with broken CTEs repaired (or at least stubbed).
    """
    known_ctes = {f.name for f in fragments}
    result: list[CTEFragment] = []

    for frag in fragments:
        if frag.is_stub:
            result.append(frag)
            continue

        input_names = ctx.cte_inputs.get(frag.name, [])
        available: set[str] = {
            f.name
            for inp in input_names
            for f in ctx.cte_schema.get(inp, [])
        }
        col_refs = _extract_col_refs(frag.sql, known_ctes)
        missing = col_refs - available - _INTERNAL_COLS

        if not missing:
            result.append(frag)
            continue

        input_schemas = {inp: ctx.cte_schema.get(inp, []) for inp in input_names}
        schema_lines = [_schema_summary(n, s) for n, s in input_schemas.items()]
        notes = (
            f"Missing columns: {', '.join(f'[{c}]' for c in sorted(missing))}. "
            f"Available in inputs — {'; '.join(schema_lines) if schema_lines else 'none'}."
        )

        repaired_sql = repair_cte_llm(frag.name, frag.sql, input_schemas, missing)

        if repaired_sql:
            result.append(
                frag.model_copy(
                    update={
                        "sql": repaired_sql,
                        "is_stub": True,
                        "llm_repaired": True,
                        "llm_repair_notes": f"LLM-repaired. {notes}",
                    }
                )
            )
        else:
            result.append(
                frag.model_copy(
                    update={
                        "is_stub": True,
                        "llm_repair_notes": notes,
                    }
                )
            )

    return result
