"""Column-reference validation pass — flags unresolvable references for manual review.

After the deterministic liveness pass, some CTEs may still reference columns
that do not exist in any upstream schema.  Common causes:

  * LLM-hallucinated column names (e.g. ``[Sum_Pre]`` when only ``[Sum_reqs]``
    exists).
  * Columns that originate from a macro stub (schema unknown).
  * Cross-file CTE references generated by the LLM chunk translator.

This module detects those gaps and annotates each broken CTE with:
  * ``is_stub = True`` — so the assembler flags it for manual review.
  * ``llm_repair_notes`` — a human-readable description of which columns are
    missing and what columns are actually available in each input CTE.

No LLM calls are made here; fixing the flagged CTEs is left to the developer.
The ``CTE_REPAIR_SYSTEM_PROMPT`` in ``llm/prompts.py`` can be used to drive a
manual or future automated repair workflow.

Usage::

    from analysis.llm_validator import repair_fragments

    fragments = repair_fragments(fragments, ctx)
"""

from __future__ import annotations

import re

from parsing.models import CTEFragment, FieldSchema
from translators.context import TranslationContext

_BRACKET_RE = re.compile(r"\[([^\]]+)\]")
_INTERNAL_COLS = {"_rn", "_stub", "_macro_stub", "_sort_order", "_deduped"}


def _extract_col_refs(sql: str, known_ctes: set[str]) -> set[str]:
    return {
        m.group(1)
        for m in _BRACKET_RE.finditer(sql)
        if m.group(1) not in _INTERNAL_COLS and m.group(1) not in known_ctes
    }


def _schema_summary(name: str, schema: list[FieldSchema]) -> str:
    if not schema:
        return f"{name}: (schema unknown)"
    cols = ", ".join(f"[{f.name}]" for f in schema)
    return f"{name}: {cols}"


def repair_fragments(
    fragments: list[CTEFragment],
    ctx: TranslationContext,
) -> list[CTEFragment]:
    """Flag CTEs with unresolvable column references for manual review.

    Non-stub CTEs are scanned for column references absent from their input
    schemas.  Each broken CTE is marked ``is_stub=True`` and annotated with
    ``llm_repair_notes`` describing exactly which columns are missing and what
    is available in each input — giving the developer the context needed to fix
    the CTE manually or pass the notes to an LLM.

    Args:
        fragments: CTEFragment list (post liveness pass).
        ctx:       TranslationContext with populated ``cte_schema`` and
                   ``cte_inputs``.

    Returns:
        Updated fragment list with broken CTEs stubbed and annotated.
    """
    known_ctes = {f.name for f in fragments}
    result: list[CTEFragment] = []

    for frag in fragments:
        if frag.is_stub:
            result.append(frag)
            continue

        input_names = ctx.cte_inputs.get(frag.name, [])
        available: set[str] = {
            f.name
            for inp in input_names
            for f in ctx.cte_schema.get(inp, [])
        }
        col_refs = _extract_col_refs(frag.sql, known_ctes)
        missing = col_refs - available - _INTERNAL_COLS

        if not missing:
            result.append(frag)
            continue

        # Build a clear diagnostic note for the developer.
        input_schemas = {inp: ctx.cte_schema.get(inp, []) for inp in input_names}
        schema_lines = [_schema_summary(n, s) for n, s in input_schemas.items()]
        notes = (
            f"Missing columns: {', '.join(f'[{c}]' for c in sorted(missing))}. "
            f"Available in inputs — {'; '.join(schema_lines) if schema_lines else 'none'}."
        )

        result.append(
            frag.model_copy(
                update={
                    "is_stub": True,
                    "llm_repair_notes": notes,
                }
            )
        )

    return result
