"""Temp-table assembler — Phase 5.

Converts an ordered list of CTEFragments into a complete, valid T-SQL stored
procedure that can be pasted directly into SSMS / Azure Data Studio and
executed on SQL Server 2016+.

Output format
-------------
    -- Generated by alteryx-to-sql-agent
    -- Source: <workflow_name>
    -- Generated: <timestamp>

    CREATE PROCEDURE [dbo].[<proc_name>]
    AS
    BEGIN
        SET NOCOUNT ON;

        SELECT * INTO #temp_name_1 FROM (
            <sql body>
        ) AS [_src];

        ...

        SELECT * INTO #temp_last FROM (
            <sql body>
        ) AS [_src];

        SELECT * FROM #temp_last;

    END;
    GO

The procedure name is derived from the workflow filename by stripping the
.yxmd extension and replacing non-alphanumeric characters with underscores.

Stub detection
--------------
Any fragment with `is_stub=True` causes the assembler to prepend a block-level
comment so the reviewer can identify incomplete sections quickly.
"""

from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path

from parsing.models import CTEFragment

_HEADER_TEMPLATE = """\
-- =============================================================================
-- Generated by alteryx-to-sql-agent
-- Source:    {workflow_name}
-- Generated: {timestamp}
-- Stubs:     {stub_count} temp table(s) require manual review
-- =============================================================================
"""

_SECTION_BANNERS: dict[str, str] = {
    "source": (
        "-- -----------------------------------------------------------------------------\n"
        "-- SOURCE LOADING\n"
        "-- -----------------------------------------------------------------------------"
    ),
    "transform": (
        "-- -----------------------------------------------------------------------------\n"
        "-- TRANSFORMATIONS\n"
        "-- -----------------------------------------------------------------------------"
    ),
    "output": (
        "-- -----------------------------------------------------------------------------\n"
        "-- OUTPUT\n"
        "-- -----------------------------------------------------------------------------"
    ),
}


def _proc_name(workflow_name: str) -> str:
    """Derive a T-SQL-safe stored procedure name from the workflow filename."""
    stem = Path(workflow_name).stem
    safe = re.sub(r"[^A-Za-z0-9_]", "_", stem)
    safe = re.sub(r"_+", "_", safe).strip("_")
    return safe or "workflow"


def _classify_fragment(frag: CTEFragment, source_ids: set[int], sink_ids: set[int]) -> str:
    if source_ids and any(tid in source_ids for tid in frag.source_tool_ids):
        return "source"
    if sink_ids and any(tid in sink_ids for tid in frag.source_tool_ids):
        return "output"
    return "transform"


def _replace_refs(sql: str, names: set[str]) -> str:
    """Replace bracketed [name] references with #name for all known temp table names."""
    for name in names:
        sql = sql.replace(f"[{name}]", f"#{name}")
    return sql


def build_sql(
    fragments: list[CTEFragment],
    workflow_name: str = "unknown",
    source_ids: set[int] | None = None,
    sink_ids: set[int] | None = None,
    engine_vars: set[str] | None = None,
) -> str:
    """Assemble CTEFragments into a T-SQL stored procedure (SQL Server 2016+).

    Args:
        fragments:      Ordered list of CTEFragments (from translate_chunk calls).
        workflow_name:  The source .yxmd filename (for the header and proc name).
        source_ids:     Tool IDs classified as sources (used for section banners).
        sink_ids:       Tool IDs classified as sinks (used for section banners).
        engine_vars:    Alteryx engine variable names found during translation
                        (e.g. ``{'WorkflowFileName'}``).  A ``DECLARE`` statement
                        is emitted for each so the user can fill in the values.

    Returns:
        A complete ``CREATE PROCEDURE … AS BEGIN … END; GO`` T-SQL string.
    """
    if not fragments:
        return "-- No temp tables generated\nSELECT 1 AS _empty;"

    stub_count = sum(1 for f in fragments if f.is_stub)
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    header = _HEADER_TEMPLATE.format(
        workflow_name=workflow_name,
        timestamp=timestamp,
        stub_count=stub_count,
    )

    all_names: set[str] = {frag.name for frag in fragments}

    _source_ids: set[int] = source_ids or set()
    _sink_ids: set[int] = sink_ids or set()
    use_sections = bool(_source_ids or _sink_ids)

    parts: list[str] = []
    current_section: str | None = None

    for frag in fragments:
        if use_sections:
            section = _classify_fragment(frag, _source_ids, _sink_ids)
            if section != current_section:
                parts.append(_SECTION_BANNERS[section])
                current_section = section

        body_sql = _replace_refs(frag.sql, all_names)
        body = _indent(body_sql, "    ")
        if frag.is_stub:
            body = "    -- !!! STUB — requires manual review !!!\n" + body

        stmt = f"SELECT * INTO #{frag.name} FROM (\n{body}\n) AS [_src];"
        parts.append(stmt)

    last_name = fragments[-1].name
    proc_name = _proc_name(workflow_name)

    # DECLARE statements for Alteryx engine variables (sorted for determinism)
    declare_block = ""
    if engine_vars:
        declares = "\n".join(
            f"    DECLARE @{v} NVARCHAR(255) = N'<replace me>';"
            for v in sorted(engine_vars)
        )
        declare_block = f"{declares}\n\n"

    # Indent the entire statement block one level inside BEGIN…END.
    statements = "\n\n".join(parts)
    inner_body = _indent(
        f"{statements}\n\nSELECT * FROM #{last_name};",
        "    ",
    )

    return (
        f"{header}\n"
        f"CREATE PROCEDURE [dbo].[{proc_name}]\n"
        f"AS\n"
        f"BEGIN\n"
        f"    SET NOCOUNT ON;\n\n"
        f"{declare_block}"
        f"{inner_body}\n\n"
        f"END;\n"
        f"GO\n"
    )


def _indent(text: str, prefix: str) -> str:
    """Indent every line of text with prefix."""
    return "\n".join(prefix + line for line in text.splitlines())
