"""CTE assembler — Phase 5.

Converts an ordered list of CTEFragments into a complete, valid T-SQL script.

Output format
-------------
    -- Generated by alteryx-to-sql-agent
    -- Source: <workflow_name>
    -- Generated: <timestamp>

    WITH
    [cte_name_1] AS (
        <sql body>
    ),
    [cte_name_2] AS (
        <sql body>
    ),
    ...
    [last_cte] AS (
        <sql body>
    )
    SELECT * FROM [last_cte];

The trailing SELECT * FROM [last_cte] makes the script immediately executable
in SSMS / Azure Data Studio.  Users can remove or replace it as needed.

Stub detection
--------------
Any fragment with `is_stub=True` causes the assembler to prepend a block-level
comment so the reviewer can identify incomplete sections quickly.
"""

from __future__ import annotations

from datetime import datetime, timezone

from parsing.models import CTEFragment

_HEADER_TEMPLATE = """\
-- =============================================================================
-- Generated by alteryx-to-sql-agent
-- Source:    {workflow_name}
-- Generated: {timestamp}
-- Stubs:     {stub_count} CTE(s) require manual review
-- =============================================================================
"""


def build_sql(
    fragments: list[CTEFragment],
    workflow_name: str = "unknown",
) -> str:
    """Assemble CTEFragments into a complete T-SQL script.

    Args:
        fragments:      Ordered list of CTEFragments (from translate_chunk calls).
        workflow_name:  The source .yxmd filename (for the header comment).

    Returns:
        A complete, formatted T-SQL string.
    """
    if not fragments:
        return "-- No CTEs generated\nSELECT 1 AS _empty;"

    stub_count = sum(1 for f in fragments if f.is_stub)
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    header = _HEADER_TEMPLATE.format(
        workflow_name=workflow_name,
        timestamp=timestamp,
        stub_count=stub_count,
    )

    cte_blocks: list[str] = []

    for frag in fragments:
        body = _indent(frag.sql, "    ")

        if frag.is_stub:
            stub_banner = "    -- !!! STUB — requires manual review !!!"
            body = stub_banner + "\n" + body

        block = f"[{frag.name}] AS (\n{body}\n)"
        cte_blocks.append(block)

    cte_section = ",\n\n".join(cte_blocks)
    last_name = fragments[-1].name

    sql = f"{header}\nWITH\n{cte_section}\n\nSELECT * FROM [{last_name}];\n"

    return sql


def _indent(text: str, prefix: str) -> str:
    """Indent every line of text with prefix."""
    return "\n".join(prefix + line for line in text.splitlines())
