"""Assembler — Phase 5.

Converts an ordered list of CTEFragments into a complete, valid T-SQL stored
procedure that can be pasted directly into SSMS / Azure Data Studio and
executed on SQL Server 2016+.

Output format
-------------
Linear chains are expressed as CTEs (WITH blocks) and only materialised to
temp tables at divergence points — where a result is consumed by more than
one downstream step, at leaf side-outputs, or at the final output.
CTE grouping is dependency-driven: each temp table's WITH block contains
exactly the transitive CTE chain that feeds into it, not merely the
preceding consecutive fragments.

    -- Generated by alteryx-to-sql-agent
    -- Source: <workflow_name>
    -- Generated: <timestamp>

    CREATE PROCEDURE [dbo].[<proc_name>]
    AS
    BEGIN
        SET NOCOUNT ON;

        -- Linear chain: A → B both feed only C
        WITH
            [step_a] AS (
                <sql body A>
            ),
            [step_b] AS (
                <sql body B>
            )
        SELECT * INTO #step_c FROM (
            <sql body C>
        ) AS [_src];

        -- Fan-out point: step_c feeds two branches, must be a temp table
        SELECT * INTO #branch1 FROM (
            <sql body>
        ) AS [_src];

        SELECT * INTO #branch2 FROM (
            <sql body>
        ) AS [_src];

        SELECT * FROM #branch2;

    END;
    GO

Materialisation rules
---------------------
A fragment is emitted as a temp table (materialised) when:
  * It is the final output fragment.
  * Its name is referenced by 2+ other fragments (fan-out).
  * Its name is referenced by 0 other fragments and it is not the final
    output (a leaf/secondary branch, e.g. a filter-false side-output).
  * It is a stub (so reviewers can see it clearly).

All other fragments (ref-count == 1, non-stub, non-final) become CTEs
within the preceding materialisation block's WITH clause.

Procedure name
--------------
Derived from the workflow filename by stripping the .yxmd extension and
replacing non-alphanumeric characters with underscores.
"""

from __future__ import annotations

import re
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

from parsing.models import CTEFragment
from assembly.inliner import collapse_fragments

_HEADER_TEMPLATE = """\
-- =============================================================================
-- Generated by alteryx-to-sql-agent
-- Source:    {workflow_name}
-- Generated: {timestamp}
-- Stubs:     {stub_count} temp table(s) require manual review
-- =============================================================================
"""

_SECTION_BANNERS: dict[str, str] = {
    "source": (
        "-- -----------------------------------------------------------------------------\n"
        "-- SOURCE LOADING\n"
        "-- -----------------------------------------------------------------------------"
    ),
    "transform": (
        "-- -----------------------------------------------------------------------------\n"
        "-- TRANSFORMATIONS\n"
        "-- -----------------------------------------------------------------------------"
    ),
    "output": (
        "-- -----------------------------------------------------------------------------\n"
        "-- OUTPUT\n"
        "-- -----------------------------------------------------------------------------"
    ),
}


def _proc_name(workflow_name: str) -> str:
    """Derive a T-SQL-safe stored procedure name from the workflow filename."""
    stem = Path(workflow_name).stem
    safe = re.sub(r"[^A-Za-z0-9_]", "_", stem)
    safe = re.sub(r"_+", "_", safe).strip("_")
    return safe or "workflow"


def _classify_fragment(frag: CTEFragment, source_ids: set[int], sink_ids: set[int]) -> str:
    if source_ids and any(tid in source_ids for tid in frag.source_tool_ids):
        return "source"
    if sink_ids and any(tid in sink_ids for tid in frag.source_tool_ids):
        return "output"
    return "transform"


def _replace_refs(sql: str, names: set[str]) -> str:
    """Replace bracketed [name] references with #name for all materialised temp table names."""
    for name in names:
        sql = sql.replace(f"[{name}]", f"#{name}")
    return sql


def _count_refs(fragments: list[CTEFragment]) -> Counter[str]:
    """Count how many other fragments reference each fragment name via [name] syntax."""
    all_names = {f.name for f in fragments}
    counts: Counter[str] = Counter()
    for frag in fragments:
        for name in all_names:
            if f"[{name}]" in frag.sql:
                counts[name] += 1
    return counts


def _group_into_cte_blocks(fragments: list[CTEFragment]) -> list[list[CTEFragment]]:
    """Group fragments into CTE blocks by dependency chain of each materialisation point.

    For each materialisation point M, BFS backwards through its transitive dependencies
    collecting any fragments with ref_count == 1 (i.e. consumed only by M's chain).
    Those fragments become CTEs in M's WITH block.  Each group is ordered by original
    topological position so the WITH clause definitions are in a valid order.

    Returns a list of groups. Within each group:
      - All but the last fragment are CTEs in a WITH clause.
      - The last fragment is the materialised temp table (SELECT * INTO #name).
    """
    if not fragments:
        return []

    all_names = {f.name for f in fragments}
    ref_counts = _count_refs(fragments)
    by_name = {f.name: f for f in fragments}

    must_materialise: set[str] = {fragments[-1].name}
    for frag in fragments:
        if frag.is_stub or ref_counts[frag.name] != 1:
            must_materialise.add(frag.name)

    def deps_of(frag: CTEFragment) -> set[str]:
        """Fragment names referenced via [name] in frag's SQL."""
        return {name for name in all_names if f"[{name}]" in frag.sql}

    assigned_as_cte: set[str] = set()
    groups: list[list[CTEFragment]] = []

    for mat_frag in fragments:
        if mat_frag.name not in must_materialise:
            continue

        # BFS backwards through CTE-eligible deps of this materialisation point.
        cte_names: set[str] = set()
        frontier = list(deps_of(mat_frag))
        visited: set[str] = {mat_frag.name}

        while frontier:
            dep_name = frontier.pop()
            if dep_name in visited:
                continue
            visited.add(dep_name)
            if dep_name in must_materialise or dep_name not in by_name:
                continue  # stop at other mat points and external table names
            if dep_name in assigned_as_cte:
                continue  # already claimed by an earlier block
            cte_names.add(dep_name)
            frontier.extend(deps_of(by_name[dep_name]))

        assigned_as_cte.update(cte_names)

        # Preserve original topological order within the group.
        group_names = cte_names | {mat_frag.name}
        group = [f for f in fragments if f.name in group_names]
        groups.append(group)

    return groups


def build_sql(
    fragments: list[CTEFragment],
    workflow_name: str = "unknown",
    source_ids: set[int] | None = None,
    sink_ids: set[int] | None = None,
    engine_vars: set[str] | None = None,
) -> str:
    """Assemble CTEFragments into a T-SQL stored procedure (SQL Server 2016+).

    Args:
        fragments:      Ordered list of CTEFragments (from translate_chunk calls).
        workflow_name:  The source .yxmd filename (for the header and proc name).
        source_ids:     Tool IDs classified as sources (used for section banners).
        sink_ids:       Tool IDs classified as sinks (used for section banners).
        engine_vars:    Alteryx engine variable names found during translation
                        (e.g. ``{'WorkflowFileName'}``).  A ``DECLARE`` statement
                        is emitted for each so the user can fill in the values.

    Returns:
        A complete ``CREATE PROCEDURE … AS BEGIN … END; GO`` T-SQL string.
    """
    if not fragments:
        return "-- No temp tables generated\nSELECT 1 AS _empty;"

    fragments = collapse_fragments(fragments)
    if not fragments:
        return "-- No temp tables generated\nSELECT 1 AS _empty;"

    stub_count = sum(1 for f in fragments if f.is_stub)
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    header = _HEADER_TEMPLATE.format(
        workflow_name=workflow_name,
        timestamp=timestamp,
        stub_count=stub_count,
    )

    _source_ids: set[int] = source_ids or set()
    _sink_ids: set[int] = sink_ids or set()
    use_sections = bool(_source_ids or _sink_ids)

    groups = _group_into_cte_blocks(list(fragments))
    # Only materialised (temp table) names get the # prefix in SQL bodies.
    # CTE names within the same WITH block stay as [name] references.
    materialised_names: set[str] = {g[-1].name for g in groups}

    parts: list[str] = []
    current_section: str | None = None

    for group in groups:
        last = group[-1]

        if use_sections:
            section = _classify_fragment(last, _source_ids, _sink_ids)
            if section != current_section:
                parts.append(_SECTION_BANNERS[section])
                current_section = section

        last_body_sql = _replace_refs(last.sql, materialised_names)
        last_body = _indent(last_body_sql, "    ")
        if last.is_stub:
            last_body = "    -- !!! STUB — requires manual review !!!\n" + last_body

        if len(group) == 1:
            stmt = f"SELECT * INTO #{last.name} FROM (\n{last_body}\n) AS [_src];"
        else:
            cte_defs: list[str] = []
            for cte_frag in group[:-1]:
                cte_body = _indent(_replace_refs(cte_frag.sql, materialised_names), "        ")
                cte_defs.append(f"    [{cte_frag.name}] AS (\n{cte_body}\n    )")
            with_clause = "WITH\n" + ",\n".join(cte_defs)
            stmt = f"{with_clause}\nSELECT * INTO #{last.name} FROM (\n{last_body}\n) AS [_src];"

        parts.append(stmt)

    last_name = groups[-1][-1].name
    proc_name = _proc_name(workflow_name)

    declare_block = ""
    if engine_vars:
        declares = "\n".join(
            f"    DECLARE @{v} NVARCHAR(255) = N'<replace me>';"
            for v in sorted(engine_vars)
        )
        declare_block = f"{declares}\n\n"

    statements = "\n\n".join(parts)
    inner_body = _indent(
        f"{statements}\n\nSELECT * FROM #{last_name};",
        "    ",
    )

    return (
        f"{header}\n"
        f"CREATE PROCEDURE [dbo].[{proc_name}]\n"
        f"AS\n"
        f"BEGIN\n"
        f"    SET NOCOUNT ON;\n\n"
        f"{declare_block}"
        f"{inner_body}\n\n"
        f"END;\n"
        f"GO\n"
    )


def _indent(text: str, prefix: str) -> str:
    """Indent every line of text with prefix."""
    return "\n".join(prefix + line for line in text.splitlines())
